const abilityMaster: AbilityData[] = [
  {'id': 1, 'nameJA': 'あくしゅう', 'nameEN': 'Stench', 'text': '臭い においを 放つことによって 攻撃した ときに 相手を ひるませることが ある。'} ,
  {'id': 2, 'nameJA': 'あめふらし', 'nameEN': 'Drizzle', 'text': '登場 したときに 天気を 雨に する。'} ,
  {'id': 3, 'nameJA': 'かそく', 'nameEN': 'Speed Boost', 'text': '毎ターン 素早さが 上がる。'} ,
  {'id': 4, 'nameJA': 'カブトアーマー', 'nameEN': 'Battle Armor', 'text': '硬い 甲羅に 守られて 相手の 攻撃が 急所に 当たらない。'} ,
  {'id': 5, 'nameJA': 'がんじょう', 'nameEN': 'Sturdy', 'text': '相手の 技を 受けても 一撃で 倒されることが ない。 一撃必殺技も 効かない。'} ,
  {'id': 6, 'nameJA': 'しめりけ', 'nameEN': 'Damp', 'text': 'あたりを 湿らせることに よって じばく などの 爆発する 技を だれも 使えなくなる。'} ,
  {'id': 7, 'nameJA': 'じゅうなん', 'nameEN': 'Limber', 'text': '柔軟な 体によって まひ状態に ならない。'} ,
  {'id': 8, 'nameJA': 'すながくれ', 'nameEN': 'Sand Veil', 'text': '砂あらしの とき 回避率が 上がる。'} ,
  {'id': 9, 'nameJA': 'せいでんき', 'nameEN': 'Static', 'text': '静電気を 体に まとい 触った 相手を まひさせる ことがある。'} ,
  {'id': 10, 'nameJA': 'ちくでん', 'nameEN': 'Volt Absorb', 'text': 'でんきタイプの 技を 受けると ダメージを 受けずに 回復する。'} ,
  {'id': 11, 'nameJA': 'ちょすい', 'nameEN': 'Water Absorb', 'text': 'みずタイプの 技を 受けると ダメージを 受けずに 回復する。'} ,
  {'id': 12, 'nameJA': 'どんかん', 'nameEN': 'Oblivious', 'text': '鈍感なので メロメロや ちょうはつ状態に ならない。'} ,
  {'id': 13, 'nameJA': 'ノーてんき', 'nameEN': 'Cloud Nine', 'text': 'あらゆる 天気の 影響が なくなって しまう。'} ,
  {'id': 14, 'nameJA': 'ふくがん', 'nameEN': 'Compound Eyes', 'text': '複眼を 持っているため 技の 命中率が 上がる。'} ,
  {'id': 15, 'nameJA': 'ふみん', 'nameEN': 'Insomnia', 'text': '眠れない 体質 なので ねむり状態に ならない。'} ,
  {'id': 16, 'nameJA': 'へんしょく', 'nameEN': 'Color Change', 'text': '相手から 受けた 技の タイプに 自分の タイプが 変化 する。'} ,
  {'id': 17, 'nameJA': 'めんえき', 'nameEN': 'Immunity', 'text': '体内に 免疫を 持っているため どく状態に ならない。'} ,
  {'id': 18, 'nameJA': 'もらいび', 'nameEN': 'Flash Fire', 'text': 'ほのおタイプの 技を 受けると 炎を もらい 自分が 出す ほのおタイプの 技が 強くなる。'} ,
  {'id': 19, 'nameJA': 'りんぷん', 'nameEN': 'Shield Dust', 'text': 'りんぷんに 守られて 技の 追加効果を 受けなくなる。'} ,
  {'id': 20, 'nameJA': 'マイペース', 'nameEN': 'Own Tempo', 'text': 'マイペースなので こんらん状態に ならない。'} ,
  {'id': 21, 'nameJA': 'きゅうばん', 'nameEN': 'Suction Cups', 'text': '吸盤で 地面に 張り付き ポケモンを 入れ替えさせる 技や 道具が 効かなくなる。'} ,
  {'id': 22, 'nameJA': 'いかく', 'nameEN': 'Intimidate', 'text': '登場 したとき 威嚇して 相手を 萎縮させ 相手の 攻撃を 下げて しまう。'} ,
  {'id': 23, 'nameJA': 'かげふみ', 'nameEN': 'Shadow Tag', 'text': '相手の 影を 踏み 逃げたり 交代 できなくする。'} ,
  {'id': 24, 'nameJA': 'さめはだ', 'nameEN': 'Rough Skin', 'text': '攻撃を 受けたとき 自分に 触れた 相手を ざらざらの 肌で キズつける。'} ,
  {'id': 25, 'nameJA': 'ふしぎなまもり', 'nameEN': 'Wonder Guard', 'text': '効果バツグンの 技しか 当たらない 不思議な 力。'} ,
  {'id': 26, 'nameJA': 'ふゆう', 'nameEN': 'Levitate', 'text': '地面から 浮くことによって じめんタイプの 技を 受けない。'} ,
  {'id': 27, 'nameJA': 'ほうし', 'nameEN': 'Effect Spore', 'text': '攻撃で 自分に 触れた 相手を どくや まひや ねむり状態に する ことがある。'} ,
  {'id': 28, 'nameJA': 'シンクロ', 'nameEN': 'Synchronize', 'text': '自分が なってしまった どくや まひや やけどを 相手に うつす。'} ,
  {'id': 29, 'nameJA': 'クリアボディ', 'nameEN': 'Clear Body', 'text': '相手の 技や 特性で 能力を 下げられない。'} ,
  {'id': 30, 'nameJA': 'しぜんかいふく', 'nameEN': 'Natural Cure', 'text': '手持ちに ひっこむと 状態異常が 治る。'} ,
  {'id': 31, 'nameJA': 'ひらいしん', 'nameEN': 'Lightning Rod', 'text': 'でんきタイプの 技を 自分に 寄せつけ ダメージを 受けずに 特攻が 上がる。'} ,
  {'id': 32, 'nameJA': 'てんのめぐみ', 'nameEN': 'Serene Grace', 'text': '天の恵みの おかげで 技の 追加効果が でやすい。'} ,
  {'id': 33, 'nameJA': 'すいすい', 'nameEN': 'Swift Swim', 'text': '天気が 雨のとき 素早さが 上がる。'} ,
  {'id': 34, 'nameJA': 'ようりょくそ', 'nameEN': 'Chlorophyll', 'text': '天気が 晴れのとき 素早さが 上がる。'} ,
  {'id': 35, 'nameJA': 'はっこう', 'nameEN': 'Illuminate', 'text': 'あたりを 明るくする ことで 野生の ポケモンに 遭遇 しやすくなる。'} ,
  {'id': 36, 'nameJA': 'トレース', 'nameEN': 'Trace', 'text': '登場 したとき 相手の 特性を トレースして 同じ 特性に なる。'} ,
  {'id': 37, 'nameJA': 'ちからもち', 'nameEN': 'Huge Power', 'text': '物理攻撃の 威力が ２倍になる。'} ,
  {'id': 38, 'nameJA': 'どくのトゲ', 'nameEN': 'Poison Point', 'text': '自分に 触った 相手を どく状態に することがある。'} ,
  {'id': 39, 'nameJA': 'せいしんりょく', 'nameEN': 'Inner Focus', 'text': '鍛えられた 精神に よって 相手の 攻撃に ひるまない。'} ,
  {'id': 40, 'nameJA': 'マグマのよろい', 'nameEN': 'Magma Armor', 'text': '熱い マグマを 身にまとい こおり状態に ならない。'} ,
  {'id': 41, 'nameJA': 'みずのベール', 'nameEN': 'Water Veil', 'text': '水のベールを 身にまとい やけど状態に ならない。'} ,
  {'id': 42, 'nameJA': 'じりょく', 'nameEN': 'Magnet Pull', 'text': 'はがねタイプの ポケモンを 磁力で 引きつけて 逃げられなくする。'} ,
  {'id': 43, 'nameJA': 'ぼうおん', 'nameEN': 'Soundproof', 'text': '音を 遮断 することに よって 音の 攻撃を 受けない。'} ,
  {'id': 44, 'nameJA': 'あめうけざら', 'nameEN': 'Rain Dish', 'text': '天気が 雨のとき 少しずつ ＨＰを 回復する。'} ,
  {'id': 45, 'nameJA': 'すなおこし', 'nameEN': 'Sand Stream', 'text': '登場 したとき 天気を 砂あらしにする。'} ,
  {'id': 46, 'nameJA': 'プレッシャー', 'nameEN': 'Pressure', 'text': 'プレッシャーを あたえて 相手の 使う 技の ＰＰを 多く 減らす。'} ,
  {'id': 47, 'nameJA': 'あついしぼう', 'nameEN': 'Thick Fat', 'text': '厚い 脂肪で 守られているので ほのおタイプと こおりタイプの 技の ダメージを 半減させる。'} ,
  {'id': 48, 'nameJA': 'はやおき', 'nameEN': 'Early Bird', 'text': 'ねむり状態に なっても ２倍の 早さで 目覚める ことが できる。'} ,
  {'id': 49, 'nameJA': 'ほのおのからだ', 'nameEN': 'Flame Body', 'text': '自分に 触った 相手を やけど状態に する ことがある。'} ,
  {'id': 50, 'nameJA': 'にげあし', 'nameEN': 'Run Away', 'text': '野生の ポケモンから 必ず 逃げられる。'} ,
  {'id': 51, 'nameJA': 'するどいめ', 'nameEN': 'Keen Eye', 'text': '鋭い 目の おかげで 命中率を 下げられない。'} ,
  {'id': 52, 'nameJA': 'かいりきバサミ', 'nameEN': 'Hyper Cutter', 'text': '力自慢の ハサミを 持っているので 相手に 攻撃を 下げられない。'} ,
  {'id': 53, 'nameJA': 'ものひろい', 'nameEN': 'Pickup', 'text': '相手の 使った 道具を 拾ってくることが ある。 冒険中も 拾ってくる。'} ,
  {'id': 54, 'nameJA': 'なまけ', 'nameEN': 'Truant', 'text': '技を 出すと 次の ターンは 休んでしまう。'} ,
  {'id': 55, 'nameJA': 'はりきり', 'nameEN': 'Hustle', 'text': '自分の 攻撃が 高くなるが 命中率が 下がる。'} ,
  {'id': 56, 'nameJA': 'メロメロボディ', 'nameEN': 'Cute Charm', 'text': '自分に 触った 相手を メロメロに することが ある。'} ,
  {'id': 57, 'nameJA': 'プラス', 'nameEN': 'Plus', 'text': 'プラスか マイナスの 特性を 持つ ポケモンが 仲間に いると 自分の 特攻が 上がる。'} ,
  {'id': 58, 'nameJA': 'マイナス', 'nameEN': 'Minus', 'text': 'プラスか マイナスの 特性を 持つ ポケモンが 仲間に いると 自分の 特攻が 上がる。'} ,
  {'id': 59, 'nameJA': 'てんきや', 'nameEN': 'Forecast', 'text': '天気の 影響を 受けて みずタイプ ほのおタイプ こおりタイプの どれかに 変化する。'} ,
  {'id': 60, 'nameJA': 'ねんちゃく', 'nameEN': 'Sticky Hold', 'text': '粘着質の 体に 道具が くっついているため 相手に 道具を 奪われない。'} ,
  {'id': 61, 'nameJA': 'だっぴ', 'nameEN': 'Shed Skin', 'text': '体の 皮を 脱ぎ捨てることで 状態異常を 治すことが ある。'} ,
  {'id': 62, 'nameJA': 'こんじょう', 'nameEN': 'Guts', 'text': '状態異常に なると 根性を だして 攻撃が 上がる。'} ,
  {'id': 63, 'nameJA': 'ふしぎなうろこ', 'nameEN': 'Marvel Scale', 'text': '状態異常に なると 不思議なウロコが 反応して 防御が 上がる。'} ,
  {'id': 64, 'nameJA': 'ヘドロえき', 'nameEN': 'Liquid Ooze', 'text': 'ヘドロ液を 吸い取った 相手は 強烈な 悪臭で ダメージを 受けて ＨＰを 減らす。'} ,
  {'id': 65, 'nameJA': 'しんりょく', 'nameEN': 'Overgrow', 'text': 'ＨＰが 減ったとき くさタイプの 技の 威力が 上がる。'} ,
  {'id': 66, 'nameJA': 'もうか', 'nameEN': 'Blaze', 'text': 'ＨＰが 減ったとき ほのおタイプの 技の 威力が 上がる。'} ,
  {'id': 67, 'nameJA': 'げきりゅう', 'nameEN': 'Torrent', 'text': 'ＨＰが 減ったとき みずタイプの 技の 威力が 上がる。'} ,
  {'id': 68, 'nameJA': 'むしのしらせ', 'nameEN': 'Swarm', 'text': 'ＨＰが 減ったとき むしタイプの 技の 威力が 上がる。'} ,
  {'id': 69, 'nameJA': 'いしあたま', 'nameEN': 'Rock Head', 'text': '反動を 受ける 技を 出しても ＨＰが 減らない。'} ,
  {'id': 70, 'nameJA': 'ひでり', 'nameEN': 'Drought', 'text': '登場 したときに 天気を 晴れに する。'} ,
  {'id': 71, 'nameJA': 'ありじごく', 'nameEN': 'Arena Trap', 'text': '戦闘で 相手を 逃げられなくする。'} ,
  {'id': 72, 'nameJA': 'やるき', 'nameEN': 'Vital Spirit', 'text': 'やる気を だすことに よって ねむり状態に ならない。'} ,
  {'id': 73, 'nameJA': 'しろいけむり', 'nameEN': 'White Smoke', 'text': '白い煙に 守られて 相手に 能力を 下げられない。'} ,
  {'id': 74, 'nameJA': 'ヨガパワー', 'nameEN': 'Pure Power', 'text': 'ヨガの 力で 物理攻撃の 威力が ２倍に なる。'} ,
  {'id': 75, 'nameJA': 'シェルアーマー', 'nameEN': 'Shell Armor', 'text': '硬い 殻に 守られ 相手の 攻撃が 急所に 当たらない。'} ,
  {'id': 76, 'nameJA': 'エアロック', 'nameEN': 'Air Lock', 'text': 'あらゆる 天気の 影響が 消えて しまう。'} ,
  {'id': 77, 'nameJA': 'ちどりあし', 'nameEN': 'Tangled Feet', 'text': 'こんらん状態の ときは 回避率が アップする。'} ,
  {'id': 78, 'nameJA': 'でんきエンジン', 'nameEN': 'Motor Drive', 'text': 'でんきタイプの 技を 受けると ダメージを 受けずに 素早さが 上がる。'} ,
  {'id': 79, 'nameJA': 'とうそうしん', 'nameEN': 'Rivalry', 'text': '性別が 同じだと 闘争心を 燃やして 強くなる。 性別が 違うと 弱くなる。'} ,
  {'id': 80, 'nameJA': 'ふくつのこころ', 'nameEN': 'Steadfast', 'text': 'ひるむ たびに 不屈の心を 燃やして 素早さが 上がる。'} ,
  {'id': 81, 'nameJA': 'ゆきがくれ', 'nameEN': 'Snow Cloak', 'text': '天気が あられのとき 回避率が 上がる。'} ,
  {'id': 82, 'nameJA': 'くいしんぼう', 'nameEN': 'Gluttony', 'text': 'ＨＰが 少なくなったら 食べる きのみを ＨＰ 半分の 時に 食べてしまう。'} ,
  {'id': 83, 'nameJA': 'いかりのつぼ', 'nameEN': 'Anger Point', 'text': '急所に 攻撃が 当たると 怒りくるって 攻撃力が 最大に なる。'} ,
  {'id': 84, 'nameJA': 'かるわざ', 'nameEN': 'Unburden', 'text': '持っていた 道具が なくなると 素早さが 上がる。'} ,
  {'id': 85, 'nameJA': 'たいねつ', 'nameEN': 'Heatproof', 'text': '耐熱の 体に よって ほのおタイプの 技の 威力を 半減させる。'} ,
  {'id': 86, 'nameJA': 'たんじゅん', 'nameEN': 'Simple', 'text': '能力 変化が いつもの ２倍に なる。'} ,
  {'id': 87, 'nameJA': 'かんそうはだ', 'nameEN': 'Dry Skin', 'text': '天気が 雨の時や みずタイプの 技で ＨＰが 回復し はれの時や ほのおタイプの 技で 減ってしまう。'} ,
  {'id': 88, 'nameJA': 'ダウンロード', 'nameEN': 'Download', 'text': '相手の 防御と 特防を くらべて 低い ほうの 能力に あわせて 自分の 攻撃か 特攻を 上げる。'} ,
  {'id': 89, 'nameJA': 'てつのこぶし', 'nameEN': 'Iron Fist', 'text': 'パンチを 使う 技の 威力が 上がる。'} ,
  {'id': 90, 'nameJA': 'ポイズンヒール', 'nameEN': 'Poison Heal', 'text': 'どく状態に なると ＨＰが 減らずに 増えていく。'} ,
  {'id': 91, 'nameJA': 'てきおうりょく', 'nameEN': 'Adaptability', 'text': '自分と おなじ タイプの 技の 威力が 上がる。'} ,
  {'id': 92, 'nameJA': 'スキルリンク', 'nameEN': 'Skill Link', 'text': '連続技を 使うと いつも 最高回数 出すことが できる。'} ,
  {'id': 93, 'nameJA': 'うるおいボディ', 'nameEN': 'Hydration', 'text': '天気が 雨のとき 状態異常が 治る。'} ,
  {'id': 94, 'nameJA': 'サンパワー', 'nameEN': 'Solar Power', 'text': '天気が 晴れると 特攻が 上がるが 毎ターン ＨＰが 減る。'} ,
  {'id': 95, 'nameJA': 'はやあし', 'nameEN': 'Quick Feet', 'text': '状態異常に なると 素早さが 上がる。'} ,
  {'id': 96, 'nameJA': 'ノーマルスキン', 'nameEN': 'Normalize', 'text': 'どんな タイプの 技でも すべて ノーマルタイプに なる。 威力が 少し 上がる。'} ,
  {'id': 97, 'nameJA': 'スナイパー', 'nameEN': 'Sniper', 'text': '攻撃を 急所に 当てると 威力が さらに 上がる。'} ,
  {'id': 98, 'nameJA': 'マジックガード', 'nameEN': 'Magic Guard', 'text': '攻撃 以外では ダメージを 受けない。'} ,
  {'id': 99, 'nameJA': 'ノーガード', 'nameEN': 'No Guard', 'text': 'ノーガード戦法に よって お互いの 出す 技が かならず 当たる ようになる。'} ,
  {'id': 100, 'nameJA': 'あとだし', 'nameEN': 'Stall', 'text': '技を 出す 順番が かならず 最後に なる。'} ,
  {'id': 101, 'nameJA': 'テクニシャン', 'nameEN': 'Technician', 'text': '威力が 低い 技の 威力を 高くして 攻撃できる。'} ,
  {'id': 102, 'nameJA': 'リーフガード', 'nameEN': 'Leaf Guard', 'text': '天気が 晴れのときは 状態異常に ならない。'} ,
  {'id': 103, 'nameJA': 'ぶきよう', 'nameEN': 'Klutz', 'text': '持っている 道具を 使うことが できない。'} ,
  {'id': 104, 'nameJA': 'かたやぶり', 'nameEN': 'Mold Breaker', 'text': '相手の 特性に ジャマされる ことなく 相手に 技を 出すことが できる。'} ,
  {'id': 105, 'nameJA': 'きょううん', 'nameEN': 'Super Luck', 'text': '強運を 持っているため 相手の 急所に 攻撃が 当たりやすい。'} ,
  {'id': 106, 'nameJA': 'ゆうばく', 'nameEN': 'Aftermath', 'text': 'ひんしに なったとき 触った 相手に ダメージを あたえる。'} ,
  {'id': 107, 'nameJA': 'きけんよち', 'nameEN': 'Anticipation', 'text': '相手の 持つ 危険な 技を 察知する ことができる。'} ,
  {'id': 108, 'nameJA': 'よちむ', 'nameEN': 'Forewarn', 'text': '登場 したとき 相手の 持つ 技を ひとつだけ 読み取る。'} ,
  {'id': 109, 'nameJA': 'てんねん', 'nameEN': 'Unaware', 'text': '相手の 能力の 変化を 無視して 攻撃が できる。'} ,
  {'id': 110, 'nameJA': 'いろめがね', 'nameEN': 'Tinted Lens', 'text': '効果が いまひとつの 技を 通常の 威力で 出すことが できる。'} ,
  {'id': 111, 'nameJA': 'フィルター', 'nameEN': 'Filter', 'text': '効果バツグンに なってしまう 攻撃の 威力を 弱める ことが できる。'} ,
  {'id': 112, 'nameJA': 'スロースタート', 'nameEN': 'Slow Start', 'text': '５ターンの あいだ 攻撃と 素早さが 半分に なる。'} ,
  {'id': 113, 'nameJA': 'きもったま', 'nameEN': 'Scrappy', 'text': 'ゴーストタイプの ポケモンに ノーマルタイプと かくとうタイプの 技を 当てることが できる。'} ,
  {'id': 114, 'nameJA': 'よびみず', 'nameEN': 'Storm Drain', 'text': 'みずタイプの 技を 自分に よせつけ ダメージは 受けずに 特攻が 上がる。'} ,
  {'id': 115, 'nameJA': 'アイスボディ', 'nameEN': 'Ice Body', 'text': '天気が あられのとき ＨＰを 少しずつ 回復 する。'} ,
  {'id': 116, 'nameJA': 'ハードロック', 'nameEN': 'Solid Rock', 'text': '効果バツグンに なってしまう 攻撃の 威力を 弱める ことが できる。'} ,
  {'id': 117, 'nameJA': 'ゆきふらし', 'nameEN': 'Snow Warning', 'text': '登場 したときに 天気を あられに する。'} ,
  {'id': 118, 'nameJA': 'みつあつめ', 'nameEN': 'Honey Gather', 'text': '戦闘が 終わったとき あまいミツを 拾うことが ある。'} ,
  {'id': 119, 'nameJA': 'おみとおし', 'nameEN': 'Frisk', 'text': '登場 したとき 相手の 持ち物を 見通すことが できる。'} ,
  {'id': 120, 'nameJA': 'すてみ', 'nameEN': 'Reckless', 'text': '反動で ダメージを 受ける 技の 威力が 上がる。'} ,
  {'id': 121, 'nameJA': 'マルチタイプ', 'nameEN': 'Multitype', 'text': '持っている プレートや Ｚクリスタルの タイプによって 自分の タイプが 変わる。'} ,
  {'id': 122, 'nameJA': 'フラワーギフト', 'nameEN': 'Flower Gift', 'text': '天気が 晴れのとき 自分と 味方の 攻撃と 特防の 能力が 上がる。'} ,
  {'id': 123, 'nameJA': 'ナイトメア', 'nameEN': 'Bad Dreams', 'text': 'ねむり状態の 相手に ダメージを あたえる。'} ,
  {'id': 124, 'nameJA': 'わるいてぐせ', 'nameEN': 'Pickpocket', 'text': '触られた 相手の 道具を 盗んで しまう。'} ,
  {'id': 125, 'nameJA': 'ちからずく', 'nameEN': 'Sheer Force', 'text': '技の 追加効果は なくなるが そのぶん 高い 威力で 技を 出すことが できる。'} ,
  {'id': 126, 'nameJA': 'あまのじゃく', 'nameEN': 'Contrary', 'text': '能力の 変化が 逆転して 上がるときに 下がり 下がるときに 上がる。'} ,
  {'id': 127, 'nameJA': 'きんちょうかん', 'nameEN': 'Unnerve', 'text': '相手を 緊張させて きのみを 食べられなく させる。'} ,
  {'id': 128, 'nameJA': 'まけんき', 'nameEN': 'Defiant', 'text': '能力を 下げられると 攻撃が ぐーんと 上がる。'} ,
  {'id': 129, 'nameJA': 'よわき', 'nameEN': 'Defeatist', 'text': 'ＨＰが 半分に なると 弱気に なって 攻撃と 特攻が 半減する。'} ,
  {'id': 130, 'nameJA': 'のろわれボディ', 'nameEN': 'Cursed Body', 'text': '攻撃を 受けると 相手の 技を かなしばり状態に することが ある。'} ,
  {'id': 131, 'nameJA': 'いやしのこころ', 'nameEN': 'Healer', 'text': '状態異常の 味方を たまに 治してあげる。'} ,
  {'id': 132, 'nameJA': 'フレンドガード', 'nameEN': 'Friend Guard', 'text': '味方の ダメージを 減らすことが できる。'} ,
  {'id': 133, 'nameJA': 'くだけるよろい', 'nameEN': 'Weak Armor', 'text': '物理技で ダメージを 受けると 防御が 下がり 素早さが ぐーんと 上がる。'} ,
  {'id': 134, 'nameJA': 'ヘヴィメタル', 'nameEN': 'Heavy Metal', 'text': '自分の 重さが ２倍に なる。'} ,
  {'id': 135, 'nameJA': 'ライトメタル', 'nameEN': 'Light Metal', 'text': '自分の 重さが 半分に なる。'} ,
  {'id': 136, 'nameJA': 'マルチスケイル', 'nameEN': 'Multiscale', 'text': 'ＨＰが 満タンの ときに 受ける ダメージが 少なくなる。'} ,
  {'id': 137, 'nameJA': 'どくぼうそう', 'nameEN': 'Toxic Boost', 'text': 'どく状態に なったとき 物理技の 威力が 上がる。'} ,
  {'id': 138, 'nameJA': 'ねつぼうそう', 'nameEN': 'Flare Boost', 'text': 'やけど状態に なったとき 特殊技の 威力が 上がる。'} ,
  {'id': 139, 'nameJA': 'しゅうかく', 'nameEN': 'Harvest', 'text': '使った きのみを 何回も 作りだす。'} ,
  {'id': 140, 'nameJA': 'テレパシー', 'nameEN': 'Telepathy', 'text': '味方の 攻撃を 読み取って 技を 回避する。'} ,
  {'id': 141, 'nameJA': 'ムラっけ', 'nameEN': 'Moody', 'text': '毎ターン 能力の どれかが ぐーんと 上がって どれかが 下がる。'} ,
  {'id': 142, 'nameJA': 'ぼうじん', 'nameEN': 'Overcoat', 'text': 'すなあらしや あられなどの ダメージを 受けない。 粉の 技を 受けない。'} ,
  {'id': 143, 'nameJA': 'どくしゅ', 'nameEN': 'Poison Touch', 'text': '触る だけで 相手を どく 状態に することがある。'} ,
  {'id': 144, 'nameJA': 'さいせいりょく', 'nameEN': 'Regenerator', 'text': '手持ちに 引っ込むと ＨＰが 少し 回復する。'} ,
  {'id': 145, 'nameJA': 'はとむね', 'nameEN': 'Big Pecks', 'text': '防御を 下げる 効果を 受けない。'} ,
  {'id': 146, 'nameJA': 'すなかき', 'nameEN': 'Sand Rush', 'text': '天気が すなあらし のとき 素早さが 上がる。'} ,
  {'id': 147, 'nameJA': 'ミラクルスキン', 'nameEN': 'Wonder Skin', 'text': '変化技を 受けにくい 体に なっている。'} ,
  {'id': 148, 'nameJA': 'アナライズ', 'nameEN': 'Analytic', 'text': 'いちばん 最後に 技を 出すと 技の 威力が 上がる。'} ,
  {'id': 149, 'nameJA': 'イリュージョン', 'nameEN': 'Illusion', 'text': '手持ちの いちばん うしろに いる ポケモンに なりきって 登場して 相手を 化かす。'} ,
  {'id': 150, 'nameJA': 'かわりもの', 'nameEN': 'Imposter', 'text': '目の前の ポケモンに 変身 してしまう。'} ,
  {'id': 151, 'nameJA': 'すりぬけ', 'nameEN': 'Infiltrator', 'text': '相手の 壁や 身代わりを すりぬけて 攻撃 できる'} ,
  {'id': 152, 'nameJA': 'ミイラ', 'nameEN': 'Mummy', 'text': '相手に 触られると 相手を ミイラに してしまう。'} ,
  {'id': 153, 'nameJA': 'じしんかじょう', 'nameEN': 'Moxie', 'text': '相手を 倒すと 自信が ついて 攻撃が 上がる。'} ,
  {'id': 154, 'nameJA': 'せいぎのこころ', 'nameEN': 'Justified', 'text': 'あくタイプの 攻撃を 受けると 正義感で 攻撃が 上がる。'} ,
  {'id': 155, 'nameJA': 'びびり', 'nameEN': 'Rattled', 'text': 'あくタイプと ゴーストタイプと むしタイプの 技を 受けると びびって 素早さが 上がる。'} ,
  {'id': 156, 'nameJA': 'マジックミラー', 'nameEN': 'Magic Bounce', 'text': '相手に だされた 変化技を 受けずに そのまま 返す ことが できる。'} ,
  {'id': 157, 'nameJA': 'そうしょく', 'nameEN': 'Sap Sipper', 'text': 'くさタイプの 技を 受けると ダメージを 受けずに 攻撃が 上がる。'} ,
  {'id': 158, 'nameJA': 'いたずらごころ', 'nameEN': 'Prankster', 'text': '変化技を 先制で 出すことが できる。'} ,
  {'id': 159, 'nameJA': 'すなのちから', 'nameEN': 'Sand Force', 'text': '天気が すなあらしの とき いわタイプと じめんタイプと はがねタイプの 威力が 上がる。'} ,
  {'id': 160, 'nameJA': 'てつのトゲ', 'nameEN': 'Iron Barbs', 'text': '自分に 触った 相手に 鉄のトゲで ダメージを あたえる。'} ,
  {'id': 161, 'nameJA': 'ダルマモード', 'nameEN': 'Zen Mode', 'text': 'ＨＰが 半分 以下に なると 姿が 変化する。'} ,
  {'id': 162, 'nameJA': 'しょうりのほし', 'nameEN': 'Victory Star', 'text': '自分や 味方の 命中率が 上がる。'} ,
  {'id': 163, 'nameJA': 'ターボブレイズ', 'nameEN': 'Turboblaze', 'text': '相手の 特性に ジャマされず 相手に 技を 出すことが できる。'} ,
  {'id': 164, 'nameJA': 'テラボルテージ', 'nameEN': 'Teravolt', 'text': '相手の 特性に ジャマされず 相手に 技を 出すことが できる。'} ,
  {'id': 165, 'nameJA': 'アロマベール', 'nameEN': 'Aroma Veil', 'text': '自分と 味方への メンタル 攻撃を 防ぐことが できる。'} ,
  {'id': 166, 'nameJA': 'フラワーベール', 'nameEN': 'Flower Veil', 'text': '味方の 草ポケモンは 能力が 下がらず 状態異常にも ならない。'} ,
  {'id': 167, 'nameJA': 'ほおぶくろ', 'nameEN': 'Cheek Pouch', 'text': 'どんな きのみでも 食べると ＨＰも 回復する。'} ,
  {'id': 168, 'nameJA': 'へんげんじざい', 'nameEN': 'Protean', 'text': '自分が 出す 技と 同じ タイプに 変化する。'} ,
  {'id': 169, 'nameJA': 'ファーコート', 'nameEN': 'Fur Coat', 'text': '相手から 受ける 物理技の ダメージが 半分に なる。'} ,
  {'id': 170, 'nameJA': 'マジシャン', 'nameEN': 'Magician', 'text': '技を 当てた 相手の 道具を 奪ってしまう。'} ,
  {'id': 171, 'nameJA': 'ぼうだん', 'nameEN': 'Bulletproof', 'text': '相手の 弾や 爆弾などの 技を 防ぐことが できる。'} ,
  {'id': 172, 'nameJA': 'かちき', 'nameEN': 'Competitive', 'text': '能力を 下げられると 特攻が ぐーんと 上がる。'} ,
  {'id': 173, 'nameJA': 'がんじょうあご', 'nameEN': 'Strong Jaw', 'text': 'あごが 頑丈で 噛む 技の 威力が 高くなる。'} ,
  {'id': 174, 'nameJA': 'フリーズスキン', 'nameEN': 'Refrigerate', 'text': 'ノーマルタイプの 技が こおりタイプに なる。 威力が 少し 上がる。'} ,
  {'id': 175, 'nameJA': 'スイートベール', 'nameEN': 'Sweet Veil', 'text': '味方の ポケモンは 眠らなくなる。'} ,
  {'id': 176, 'nameJA': 'バトルスイッチ', 'nameEN': 'Stance Change', 'text': '攻撃技を 出すと ブレードフォルムに 技 キングシールドを 出すと シールドフォルムに 変化する。'} ,
  {'id': 177, 'nameJA': 'はやてのつばさ', 'nameEN': 'Gale Wings', 'text': 'ＨＰが 満タン だと ひこうタイプの 技を 先制で 出すことが できる。'} ,
  {'id': 178, 'nameJA': 'メガランチャー', 'nameEN': 'Mega Launcher', 'text': '波動の 技の 威力が 高くなる。'} ,
  {'id': 179, 'nameJA': 'くさのけがわ', 'nameEN': 'Grass Pelt', 'text': 'グラスフィールドのとき 防御が 上がる。'} ,
  {'id': 180, 'nameJA': 'きょうせい', 'nameEN': 'Symbiosis', 'text': '味方が 道具を 使うと 自分の 持っている 道具を 味方に 渡す。'} ,
  {'id': 181, 'nameJA': 'かたいツメ', 'nameEN': 'Tough Claws', 'text': '相手に 接触する 技の 威力が 高くなる。'} ,
  {'id': 182, 'nameJA': 'フェアリースキン', 'nameEN': 'Pixilate', 'text': 'ノーマルタイプの 技が フェアリータイプになる。 威力が 少し 上がる。'} ,
  {'id': 183, 'nameJA': 'ぬめぬめ', 'nameEN': 'Gooey', 'text': '攻撃で 自分に 触れた 相手の 素早さを 下げる。'} ,
  {'id': 184, 'nameJA': 'スカイスキン', 'nameEN': 'Aerilate', 'text': 'ノーマルタイプの 技が ひこうタイプになる。 威力が 少し 上がる。'} ,
  {'id': 185, 'nameJA': 'おやこあい', 'nameEN': 'Parental Bond', 'text': '親子 ２匹で ２回 攻撃することが できる。'} ,
  {'id': 186, 'nameJA': 'ダークオーラ', 'nameEN': 'Dark Aura', 'text': '全員の あくタイプの 技が 強くなる。'} ,
  {'id': 187, 'nameJA': 'フェアリーオーラ', 'nameEN': 'Fairy Aura', 'text': '全員の フェアリータイプの 技が 強くなる。'} ,
  {'id': 188, 'nameJA': 'オーラブレイク', 'nameEN': 'Aura Break', 'text': 'オーラの 効果を 逆転させて 威力を 下げる。'} ,
  {'id': 189, 'nameJA': 'はじまりのうみ', 'nameEN': 'Primordial Sea', 'text': 'ほのおタイプの 攻撃を 受けない 天気にする。'} ,
  {'id': 190, 'nameJA': 'おわりのだいち', 'nameEN': 'Desolate Land', 'text': 'みずタイプの 攻撃を 受けない 天気にする。'} ,
  {'id': 191, 'nameJA': 'デルタストリーム', 'nameEN': 'Delta Stream', 'text': 'ひこうタイプの 弱点が なくなる 天気にする。'} ,
  {'id': 192, 'nameJA': 'じきゅうりょく', 'nameEN': 'Stamina', 'text': '攻撃を 受けると 防御が 上がる。'} ,
  {'id': 193, 'nameJA': 'にげごし', 'nameEN': 'Wimp Out', 'text': 'ＨＰが 半分に なると あわてて 逃げ出して 手持ちに 引っ込んで しまう。'} ,
  {'id': 194, 'nameJA': 'ききかいひ', 'nameEN': 'Emergency Exit', 'text': 'ＨＰが 半分に なると 危険を 回避するため 手持ちに 引っ込んで しまう。'} ,
  {'id': 195, 'nameJA': 'みずがため', 'nameEN': 'Water Compaction', 'text': 'みずタイプの 技を 受けると 防御が ぐーんと 上がる。'} ,
  {'id': 196, 'nameJA': 'ひとでなし', 'nameEN': 'Merciless', 'text': 'どく状態の 相手を 攻撃すると かならず 急所に 当たる。'} ,
  {'id': 197, 'nameJA': 'リミットシールド', 'nameEN': 'Shields Down', 'text': 'ＨＰが 半分に なると 殻が 壊れて 攻撃的に なる。'} ,
  {'id': 198, 'nameJA': 'はりこみ', 'nameEN': 'Stakeout', 'text': '交代で 出てきた 相手に ２倍の ダメージで 攻撃 できる。'} ,
  {'id': 199, 'nameJA': 'すいほう', 'nameEN': 'Water Bubble', 'text': '自分に 対する ほのおタイプの 技の 威力を 下げる。 やけど しない。'} ,
  {'id': 200, 'nameJA': 'はがねつかい', 'nameEN': 'Steelworker', 'text': 'はがねタイプの 技の 威力が 上がる。'} ,
  {'id': 201, 'nameJA': 'ぎゃくじょう', 'nameEN': 'Berserk', 'text': '相手の 攻撃で ＨＰが 半分に なると 特攻が 上がる。'} ,
  {'id': 202, 'nameJA': 'ゆきかき', 'nameEN': 'Slush Rush', 'text': '天気が あられ のとき 素早さが 上がる。'} ,
  {'id': 203, 'nameJA': 'えんかく', 'nameEN': 'Long Reach', 'text': 'すべての 技を 相手に 接触 しないで 出すことが できる。'} ,
  {'id': 204, 'nameJA': 'うるおいボイス', 'nameEN': 'Liquid Voice', 'text': 'すべての 音技が みずタイプに なる。'} ,
  {'id': 205, 'nameJA': 'ヒーリングシフト', 'nameEN': 'Triage', 'text': '回復技を 先制で 出すことが できる。'} ,
  {'id': 206, 'nameJA': 'エレキスキン', 'nameEN': 'Galvanize', 'text': 'ノーマルタイプの 技が でんきタイプになる。 威力が 少し 上がる。'} ,
  {'id': 207, 'nameJA': 'サーフテール', 'nameEN': 'Surge Surfer', 'text': 'エレキフィールド のとき 素早さが ２倍に なる。'} ,
  {'id': 208, 'nameJA': 'ぎょぐん', 'nameEN': 'Schooling', 'text': 'ＨＰが 多いときは 群れて 強くなる。 ＨＰの 残りが 少なくなると 群れは 散り散りに なってしまう。'} ,
  {'id': 209, 'nameJA': 'ばけのかわ', 'nameEN': 'Disguise', 'text': '体を 被う 化けの皮で １回 攻撃を 防ぐことが できる。'} ,
  {'id': 210, 'nameJA': 'きずなへんげ', 'nameEN': 'Battle Bond', 'text': '相手を 倒すと トレーナーとの キズナが 深まり サトシゲッコウガに 変化する。みずしゅりけんが 強くなる。'} ,
  {'id': 211, 'nameJA': 'スワームチェンジ', 'nameEN': 'Power Construct', 'text': 'ＨＰが 半分に なると セルたちが 応援に 駆けつけ パーフェクトフォルムに 姿を 変える。'} ,
  {'id': 212, 'nameJA': 'ふしょく', 'nameEN': 'Corrosion', 'text': 'はがねタイプや どくタイプも どく状態に することが できる。'} ,
  {'id': 213, 'nameJA': 'ぜったいねむり', 'nameEN': 'Comatose', 'text': 'つねに 夢うつつの 状態で 絶対に 目覚めない。 眠ったまま 攻撃が できる。'} ,
  {'id': 214, 'nameJA': 'じょおうのいげん', 'nameEN': 'Queenly Majesty', 'text': '相手に 威圧感を あたえ こちらに むかって 先制技を 出せない ようにする。'} ,
  {'id': 215, 'nameJA': 'とびだすなかみ', 'nameEN': 'Innards Out', 'text': '相手に 倒されたとき ＨＰの 残りの ぶんだけ 相手に ダメージを あたえる。'} ,
  {'id': 216, 'nameJA': 'おどりこ', 'nameEN': 'Dancer', 'text': 'だれかが 踊り技を 使うと 自分も それに 続いて 踊り技を 出すことが できる。'} ,
  {'id': 217, 'nameJA': 'バッテリー', 'nameEN': 'Battery', 'text': '味方の 特殊技の 威力を 上げる。'} ,
  {'id': 218, 'nameJA': 'もふもふ', 'nameEN': 'Fluffy', 'text': '相手から 受けた 接触する 技の ダメージを 半減するが ほのおタイプの 技の ダメージは ２倍になる。'} ,
  {'id': 219, 'nameJA': 'ビビッドボディ', 'nameEN': 'Dazzling', 'text': '相手を びっくり させて こちらに むかって 先制技を 出せない ようにする。'} ,
  {'id': 220, 'nameJA': 'ソウルハート', 'nameEN': 'Soul-Heart', 'text': 'ポケモンが ひんしに なるたびに 特攻が 上がる。'} ,
  {'id': 221, 'nameJA': 'カーリーヘアー', 'nameEN': 'Tangling Hair', 'text': '攻撃で 自分に 触れた 相手の 素早さを 下げる。'} ,
  {'id': 222, 'nameJA': 'レシーバー', 'nameEN': 'Receiver', 'text': '倒された 味方の 特性を 受け継いで 同じ 特性に なる。'} ,
  {'id': 223, 'nameJA': 'かがくのちから', 'nameEN': 'Power of Alchemy', 'text': '倒された 味方の 特性を 受け継ぎ 同じ 特性に 変わる。'} ,
  {'id': 224, 'nameJA': 'ビーストブースト', 'nameEN': 'Beast Boost', 'text': '相手を 倒したとき 自分の いちばん 高い 能力が 上がる。'} ,
  {'id': 225, 'nameJA': 'ＡＲシステム', 'nameEN': 'RKS System', 'text': '持っている メモリで 自分の タイプが 変わる。'} ,
  {'id': 226, 'nameJA': 'エレキメイカー', 'nameEN': 'Electric Surge', 'text': '登場 したときに エレキフィールドを はりめぐらせる。'} ,
  {'id': 227, 'nameJA': 'サイコメイカー', 'nameEN': 'Psychic Surge', 'text': '登場 したときに サイコフィールドを はりめぐらせる。'} ,
  {'id': 228, 'nameJA': 'ミストメイカー', 'nameEN': 'Misty Surge', 'text': '登場 したときに ミストフィールドを はりめぐらせる。'} ,
  {'id': 229, 'nameJA': 'グラスメイカー', 'nameEN': 'Grassy Surge', 'text': '登場 したときに グラスフィールドを はりめぐらせる。'} ,
  {'id': 230, 'nameJA': 'メタルプロテクト', 'nameEN': 'Full Metal Body', 'text': '相手の 技や 特性で 能力を 下げられない。'} ,
  {'id': 231, 'nameJA': 'ファントムガード', 'nameEN': 'Shadow Shield', 'text': 'ＨＰが 満タンの ときに 受ける ダメージが 少なくなる。'} ,
  {'id': 232, 'nameJA': 'プリズムアーマー', 'nameEN': 'Prism Armor', 'text': '効果バツグンに なってしまう 攻撃の 威力を 弱める ことが できる。'} ,
  {'id': 233, 'nameJA': 'ブレインフォース', 'nameEN': 'Neuroforce', 'text': '効果バツグンの 攻撃で 威力が さらに 上がる。'} ,
  {'id': 234, 'nameJA': 'ふとうのけん', 'nameEN': 'Intrepid Sword', 'text': '登場 したときに 攻撃が 上がる。'} ,
  {'id': 235, 'nameJA': 'ふくつのたて', 'nameEN': 'Dauntless Shield', 'text': '登場 したときに 防御が 上がる。'} ,
  {'id': 236, 'nameJA': 'リベロ', 'nameEN': 'Libero', 'text': '自分が 出す 技と 同じ タイプに 変化する。'} ,
  {'id': 237, 'nameJA': 'たまひろい', 'nameEN': 'Ball Fetch', 'text': '道具を 持っていない 場合 １回目に 投げて 失敗 した モンスターボールを 拾ってくる。'} ,
  {'id': 238, 'nameJA': 'わたげ', 'nameEN': 'Cotton Down', 'text': '攻撃を 受けると わたげを ばらまいて 自分以外の ポケモン すべての 素早さを 下げる。'} ,
  {'id': 239, 'nameJA': 'スクリューおびれ', 'nameEN': 'Propeller Tail', 'text': '相手の 技を 引き受ける 特性や 技の 影響を 無視 できる。'} ,
  {'id': 240, 'nameJA': 'ミラーアーマー', 'nameEN': 'Mirror Armor', 'text': '自分が 受けた 能力 ダウンの 効果 だけを 跳ね返す。'} ,
  {'id': 241, 'nameJA': 'うのミサイル', 'nameEN': 'Gulp Missile', 'text': 'なみのりか ダイビングを すると 獲物を くわえてくる。 ダメージを 受けると 獲物を 吐きだして 攻撃。'} ,
  {'id': 242, 'nameJA': 'すじがねいり', 'nameEN': 'Stalwart', 'text': '相手の 技を 引き受ける 特性や 技の 影響を 無視 できる。'} ,
  {'id': 243, 'nameJA': 'じょうききかん', 'nameEN': 'Steam Engine', 'text': 'みずタイプ ほのおタイプの 技を 受けると 素早さが ぐぐーんと 上がる。'} ,
  {'id': 244, 'nameJA': 'パンクロック', 'nameEN': 'Punk Rock', 'text': '音技の 威力が 上がる。 受けた 音技の ダメージは 半分に なる。'} ,
  {'id': 245, 'nameJA': 'すなはき', 'nameEN': 'Sand Spit', 'text': '攻撃を 受けると 砂あらしを 起こす。'} ,
  {'id': 246, 'nameJA': 'こおりのりんぷん', 'nameEN': 'Ice Scales', 'text': 'こおりのりんぷんに 守られて 特殊攻撃で 受ける ダメージが 半減 する。'} ,
  {'id': 247, 'nameJA': 'じゅくせい', 'nameEN': 'Ripen', 'text': '熟成 させることで きのみの 効果が 倍に なる。'} ,
  {'id': 248, 'nameJA': 'アイスフェイス', 'nameEN': 'Ice Face', 'text': '物理攻撃は 頭の 氷が みがわりに なるが 姿も 変わる。 氷は あられが 降ると 元に戻る。'} ,
  {'id': 249, 'nameJA': 'パワースポット', 'nameEN': 'Power Spot', 'text': '隣に いるだけで 技の 威力が 上がる。'} ,
  {'id': 250, 'nameJA': 'ぎたい', 'nameEN': 'Mimicry', 'text': 'フィールドの 状態に あわせて ポケモンの タイプが 変わる。'} ,
  {'id': 251, 'nameJA': 'バリアフリー', 'nameEN': 'Screen Cleaner', 'text': '登場 したときに 敵と 味方の ひかりのかべ リフレクター オーロラベールの 効果が 消える。'} ,
  {'id': 252, 'nameJA': 'はがねのせいしん', 'nameEN': 'Steely Spirit', 'text': '味方の はがねタイプの 攻撃の 威力が 上がる。'} ,
  {'id': 253, 'nameJA': 'ほろびのボディ', 'nameEN': 'Perish Body', 'text': '接触する 技を 受けると お互い ３ターン たつと ひんしになる。 交代すると 効果は なくなる。'} ,
  {'id': 254, 'nameJA': 'さまようたましい', 'nameEN': 'Wandering Spirit', 'text': '接触する 技で 攻撃 してきた ポケモンと 特性を 入れ替える。'} ,
  {'id': 255, 'nameJA': 'ごりむちゅう', 'nameEN': 'Gorilla Tactics', 'text': '攻撃は 上がるが 最初に 選んだ 技しか 出せなくなる。'} ,
  {'id': 256, 'nameJA': 'かがくへんかガス', 'nameEN': 'Neutralizing Gas', 'text': 'かがくへんかガスの ポケモンが 場にいると すべての ポケモンの 特性の 効果が 消えたり 発動 しなくなる。'} ,
  {'id': 257, 'nameJA': 'パステルベール', 'nameEN': 'Pastel Veil', 'text': '自分も 味方も どくの 状態異常を 受けなくなる。'} ,
  {'id': 258, 'nameJA': 'はらぺこスイッチ', 'nameEN': 'Hunger Switch', 'text': 'ターンの 終わりに まんぷくもよう はらぺこもよう まんぷくもよう……と 交互に 姿を 変える。'} ,
  {'id': 259, 'nameJA': 'クイックドロウ', 'nameEN': 'Quick Draw', 'text': '相手より 先に 行動できることが ある。'} ,
  {'id': 260, 'nameJA': 'ふかしのこぶし', 'nameEN': 'Unseen Fist', 'text': '相手に 接触する 技なら 守りの 効果を 無視して 攻撃することが できる。'} ,
  {'id': 261, 'nameJA': 'きみょうなくすり', 'nameEN': 'Curious Medicine', 'text': '登場 したときに 貝がらから 薬を 振りまいて 味方の 能力変化を 元に戻す。'} ,
  {'id': 262, 'nameJA': 'トランジスタ', 'nameEN': 'Transistor', 'text': 'でんきタイプの 技の 威力が 上がる。'} ,
  {'id': 263, 'nameJA': 'りゅうのあぎと', 'nameEN': 'Dragon’s Maw', 'text': 'ドラゴンタイプの 技の 威力が 上がる。'} ,
  {'id': 264, 'nameJA': 'しろのいななき', 'nameEN': 'Chilling Neigh', 'text': '相手を 倒すと 冷たい 声で いなないて 攻撃が 上がる。'} ,
  {'id': 265, 'nameJA': 'くろのいななき', 'nameEN': 'Grim Neigh', 'text': '相手を 倒すと 恐ろしい 声で いなないて 特攻が 上がる。'} ,
  {'id': 266, 'nameJA': 'じんばいったい', 'nameEN': 'As One', 'text': 'バドレックスの きんちょうかんと ブリザポスの しろのいななきの 二つの 特性を あわせ持つ。'} ,
  {'id': 267, 'nameJA': 'じんばいったい', 'nameEN': 'As One', 'text': 'バドレックスの きんちょうかんと レイスポスの くろのいななきの 二つの 特性を あわせ持つ。'} ,
  {'id': 268, 'nameJA': 'とれないにおい', 'nameEN': 'Lingering Aroma', 'text': ''} ,
  {'id': 269, 'nameJA': 'こぼれダネ', 'nameEN': 'Seed Sower', 'text': ''} ,
  {'id': 270, 'nameJA': 'ねつこうかん', 'nameEN': 'Thermal Exchange', 'text': ''} ,
  {'id': 271, 'nameJA': 'いかりのこうら', 'nameEN': 'Anger Shell', 'text': ''} ,
  {'id': 272, 'nameJA': 'きよめのしお', 'nameEN': 'Purifying Salt', 'text': ''} ,
  {'id': 273, 'nameJA': 'こんがりボディ', 'nameEN': 'Well-Baked Body', 'text': ''} ,
  {'id': 274, 'nameJA': 'かぜのり', 'nameEN': 'Wind Rider', 'text': ''} ,
  {'id': 275, 'nameJA': 'ばんけん', 'nameEN': 'Guard Dog', 'text': ''} ,
  {'id': 276, 'nameJA': 'いわはこび', 'nameEN': 'Rocky Payload', 'text': ''} ,
  {'id': 277, 'nameJA': 'ふうりょくでんき', 'nameEN': 'Wind Power', 'text': ''} ,
  {'id': 278, 'nameJA': 'マイティチェンジ', 'nameEN': 'Zero to Hero', 'text': ''} ,
  {'id': 279, 'nameJA': 'しれいとう', 'nameEN': 'Commander', 'text': ''} ,
  {'id': 280, 'nameJA': 'でんきにかえる', 'nameEN': 'Electromorphosis', 'text': ''} ,
  {'id': 281, 'nameJA': 'こだいかっせい', 'nameEN': 'Protosynthesis', 'text': ''} ,
  {'id': 282, 'nameJA': 'クォークチャージ', 'nameEN': 'Quark Drive', 'text': ''} ,
  {'id': 283, 'nameJA': 'おうごんのからだ', 'nameEN': 'Good as Gold', 'text': ''} ,
  {'id': 284, 'nameJA': 'わざわいのうつわ', 'nameEN': 'Vessel of Ruin', 'text': ''} ,
  {'id': 285, 'nameJA': 'わざわいのつるぎ', 'nameEN': 'Sword of Ruin', 'text': ''} ,
  {'id': 286, 'nameJA': 'わざわいのおふだ', 'nameEN': 'Tablets of Ruin', 'text': ''} ,
  {'id': 287, 'nameJA': 'わざわいのたま', 'nameEN': 'Beads of Ruin', 'text': ''} ,
  {'id': 288, 'nameJA': 'ひひいろのこどう', 'nameEN': 'Orichalcum Pulse', 'text': ''} ,
  {'id': 289, 'nameJA': 'ハドロンエンジン', 'nameEN': 'Hadron Engine', 'text': ''} ,
  {'id': 290, 'nameJA': 'びんじょう', 'nameEN': 'Opportunist', 'text': ''} ,
  {'id': 291, 'nameJA': 'はんすう', 'nameEN': 'Cud Chew', 'text': ''} ,
  {'id': 292, 'nameJA': 'きれあじ', 'nameEN': 'Sharpness', 'text': ''} ,
  {'id': 293, 'nameJA': 'そうだいしょう', 'nameEN': 'Supreme Overlord', 'text': ''} ,
  {'id': 294, 'nameJA': 'きょうえん', 'nameEN': 'Costar', 'text': ''} ,
  {'id': 295, 'nameJA': 'どくげしょう', 'nameEN': 'Toxic Debris', 'text': ''} ,
  {'id': 296, 'nameJA': 'テイルアーマー', 'nameEN': 'Armor Tail', 'text': ''} ,
  {'id': 297, 'nameJA': 'どしょく', 'nameEN': 'Earth Eater', 'text': ''} ,
  {'id': 298, 'nameJA': 'きんしのちから', 'nameEN': 'Mycelium Might', 'text': ''} ,
]
