


const regPokemon: Register = new Register();

// フィールド
const fieldStatus = new Field;

// 乱数
let randomList: number[] = []


const parameterSix: string[] = [
  'hitPoint',
  'attack',
  'defense',
  'specialAttack',
  'specialDefense',
  'speed'
]

const parameterFive: string[] = [
  'attack',
  'defense',
  'specialAttack',
  'specialDefense',
  'speed'
]

const natureList: NatureType[] = [
  'てれや',
  'さみしがり',
  'いじっぱり',
  'やんちゃ',
  'ゆうかん',
  'ずぶとい',
  'がんばりや',
  'わんぱく',
  'のうてんき',
  'のんき',
  'ひかえめ',
  'おっとり',
  'すなお',
  'うっかりや',
  'れいせい',
  'おだやか',
  'おとなしい',
  'しんちょう',
  'きまぐれ',
  'なまいき',
  'おくびょう',
  'せっかち',
  'ようき',
  'むじゃき',
  'まじめ'
]


// タイプのカラーコード
// https://wiki.xn--rckteqa2e.com/wiki/%E3%82%AB%E3%83%86%E3%82%B4%E3%83%AA:%E8%89%B2%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88_%E3%82%BF%E3%82%A4%E3%83%97%E5%88%A5
const typeColor: TypeColorType[] = [
  { name: 'あく', light: 'A29288', normal: '705848', dark: '49392F', isOK: true },
  { name: 'いわ', light: 'D1C17D', normal: 'B8A038', dark: '786824', isOK: true },
  { name: 'エスパー', light: 'FA92B2', normal: 'F85888', dark: 'A13959', isOK: true },
  { name: 'かくとう', light: 'D67873', normal: 'C03028', dark: '7D1F1A', isOK: true },
  { name: 'くさ', light: 'A7DB8D', normal: '78C850', dark: '4E8234', isOK: true },
  { name: 'ゴースト', light: 'A292BC', normal: '705898', dark: '493963', isOK: true },
  { name: 'こおり', light: 'BCE6E6', normal: '98D8D8', dark: '638D8D', isOK: true },
  { name: 'じめん', light: 'EBD69D', normal: 'E0C068', dark: '927D44', isOK: true },
  { name: 'でんき', light: 'FAE078', normal: 'F8D030', dark: 'A1871F', isOK: true },
  { name: 'どく', light: 'C183C1', normal: 'A040A0', dark: '682A68', isOK: true },
  { name: 'ドラゴン', light: 'A27DFA', normal: '7038F8', dark: '4924A1', isOK: true },
  { name: 'ノーマル', light: 'C6C6A7', normal: 'A8A878', dark: '6D6D4E', isOK: true },
  { name: 'はがね', light: 'D1D1E0', normal: 'B8B8D0', dark: '787887', isOK: true },
  { name: 'ひこう', light: 'C6B7F5', normal: 'A890F0', dark: '6D5E9C', isOK: true },
  { name: 'フェアリー', light: 'F4BDC9', normal: 'EE99AC', dark: '9B6470', isOK: true },
  { name: 'ほのお', light: 'F5AC78', normal: 'F08030', dark: '9C531F', isOK: true },
  { name: 'みず', light: '9DB7F5', normal: '6890F0', dark: '445E9C', isOK: true },
  { name: 'むし', light: 'C6D16E', normal: 'A8B820', dark: '6D7815', isOK: true },
  { name: '不明', light: '9DC1B7', normal: '68A090', dark: '44685E', isOK: true }
]

// タイプ相性
const typeCompatibility: TypeCompatibilityType[] = [
  { atkType: 'Normal', rate: [
    { defType: 'Normal', rate: 1.0 },
    { defType: 'Fire', rate: 1.0 },
    { defType: 'Water', rate: 1.0 },
    { defType: 'Electric', rate: 1.0 },
    { defType: 'Grass', rate: 1.0 },
    { defType: 'Ice', rate: 1.0 },
    { defType: 'Fighting', rate: 1.0 },
    { defType: 'Poison', rate: 1.0 },
    { defType: 'Ground', rate:1.0 },
    { defType: 'Flying', rate: 1.0 },
    { defType: 'Psychic', rate: 1.0 },
    { defType: 'Bug', rate: 1.0 },
    { defType: 'Rock', rate: 0.5 },
    { defType: 'Ghost', rate: 0.0 },
    { defType: 'Dragon', rate: 1.0 },
    { defType: 'Dark', rate: 1.0 },
    { defType: 'Steel', rate: 0.5 },
    { defType: 'Fairy', rate: 1.0 },
  ]},
  { atkType: 'Fire', rate: [
    { defType: 'Normal', rate: 1.0 },
    { defType: 'Fire', rate: 0.5 },
    { defType: 'Water', rate: 0.5 },
    { defType: 'Electric', rate: 1.0 },
    { defType: 'Grass', rate: 2.0 },
    { defType: 'Ice', rate: 2.0 },
    { defType: 'Fighting', rate: 1.0 },
    { defType: 'Poison', rate: 1.0 },
    { defType: 'Ground', rate:1.0 },
    { defType: 'Flying', rate: 1.0 },
    { defType: 'Psychic', rate: 1.0 },
    { defType: 'Bug', rate: 2.0 },
    { defType: 'Rock', rate: 0.5 },
    { defType: 'Ghost', rate: 1.0 },
    { defType: 'Dragon', rate: 0.5 },
    { defType: 'Dark', rate: 1.0 },
    { defType: 'Steel', rate: 2.0 },
    { defType: 'Fairy', rate: 1.0 },
  ]},
  { atkType: 'Water', rate: [
    { defType: 'Normal', rate: 1.0 },
    { defType: 'Fire', rate: 2.0 },
    { defType: 'Water', rate: 0.5 },
    { defType: 'Electric', rate: 1.0 },
    { defType: 'Grass', rate: 0.5 },
    { defType: 'Ice', rate: 1.0 },
    { defType: 'Fighting', rate: 1.0 },
    { defType: 'Poison', rate: 1.0 },
    { defType: 'Ground', rate:2.0 },
    { defType: 'Flying', rate: 1.0 },
    { defType: 'Psychic', rate: 1.0 },
    { defType: 'Bug', rate: 1.0 },
    { defType: 'Rock', rate: 2.0 },
    { defType: 'Ghost', rate: 1.0 },
    { defType: 'Dragon', rate: 0.5 },
    { defType: 'Dark', rate: 1.0 },
    { defType: 'Steel', rate: 1.0 },
    { defType: 'Fairy', rate: 1.0 },
  ]},
  { atkType: 'Electric', rate: [
    { defType: 'Normal', rate: 1.0 },
    { defType: 'Fire', rate: 1.0 },
    { defType: 'Water', rate: 2.0 },
    { defType: 'Electric', rate: 0.5 },
    { defType: 'Grass', rate: 0.5 },
    { defType: 'Ice', rate: 1.0 },
    { defType: 'Fighting', rate: 1.0 },
    { defType: 'Poison', rate: 1.0 },
    { defType: 'Ground', rate:0.0 },
    { defType: 'Flying', rate: 2.0 },
    { defType: 'Psychic', rate: 1.0 },
    { defType: 'Bug', rate: 1.0 },
    { defType: 'Rock', rate: 1.0 },
    { defType: 'Ghost', rate: 1.0 },
    { defType: 'Dragon', rate: 0.5 },
    { defType: 'Dark', rate: 1.0 },
    { defType: 'Steel', rate: 1.0 },
    { defType: 'Fairy', rate: 1.0 },
  ]},
  { atkType: 'Grass', rate: [
    { defType: 'Normal', rate: 1.0 },
    { defType: 'Fire', rate: 0.5 },
    { defType: 'Water', rate: 2.0 },
    { defType: 'Electric', rate: 1.0 },
    { defType: 'Grass', rate: 0.5 },
    { defType: 'Ice', rate: 1.0 },
    { defType: 'Fighting', rate: 1.0 },
    { defType: 'Poison', rate: 0.5 },
    { defType: 'Ground', rate:2.0 },
    { defType: 'Flying', rate: 0.5 },
    { defType: 'Psychic', rate: 1.0 },
    { defType: 'Bug', rate: 0.5 },
    { defType: 'Rock', rate: 2.0 },
    { defType: 'Ghost', rate: 1.0 },
    { defType: 'Dragon', rate: 0.5 },
    { defType: 'Dark', rate: 1.0 },
    { defType: 'Steel', rate: 0.5 },
    { defType: 'Fairy', rate: 1.0 },
  ]},
  { atkType: 'Ice', rate: [
    { defType: 'Normal', rate: 1.0 },
    { defType: 'Fire', rate: 0.5 },
    { defType: 'Water', rate: 0.5 },
    { defType: 'Electric', rate: 1.0 },
    { defType: 'Grass', rate: 2.0 },
    { defType: 'Ice', rate: 0.5 },
    { defType: 'Fighting', rate: 1.0 },
    { defType: 'Poison', rate: 1.0 },
    { defType: 'Ground', rate:2.0 },
    { defType: 'Flying', rate: 2.0 },
    { defType: 'Psychic', rate: 1.0 },
    { defType: 'Bug', rate: 1.0 },
    { defType: 'Rock', rate: 1.0 },
    { defType: 'Ghost', rate: 1.0 },
    { defType: 'Dragon', rate: 2.0 },
    { defType: 'Dark', rate: 1.0 },
    { defType: 'Steel', rate: 0.5 },
    { defType: 'Fairy', rate: 1.0 },
  ]},
  { atkType: 'Fighting', rate: [
    { defType: 'Normal', rate: 2.0 },
    { defType: 'Fire', rate: 1.0 },
    { defType: 'Water', rate: 1.0 },
    { defType: 'Electric', rate: 1.0 },
    { defType: 'Grass', rate: 1.0 },
    { defType: 'Ice', rate: 2.0 },
    { defType: 'Fighting', rate: 1.0 },
    { defType: 'Poison', rate: 0.5 },
    { defType: 'Ground', rate:1.0 },
    { defType: 'Flying', rate: 0.5 },
    { defType: 'Psychic', rate: 0.5 },
    { defType: 'Bug', rate: 0.5 },
    { defType: 'Rock', rate: 2.0 },
    { defType: 'Ghost', rate: 0.0 },
    { defType: 'Dragon', rate: 1.0 },
    { defType: 'Dark', rate: 2.0 },
    { defType: 'Steel', rate: 2.0 },
    { defType: 'Fairy', rate: 0.5 },
  ]},
  { atkType: 'Poison', rate: [
    { defType: 'Normal', rate: 1.0 },
    { defType: 'Fire', rate: 1.0 },
    { defType: 'Water', rate: 1.0 },
    { defType: 'Electric', rate: 1.0 },
    { defType: 'Grass', rate: 2.0 },
    { defType: 'Ice', rate: 1.0 },
    { defType: 'Fighting', rate: 1.0 },
    { defType: 'Poison', rate: 0.5 },
    { defType: 'Ground', rate:0.5 },
    { defType: 'Flying', rate: 1.0 },
    { defType: 'Psychic', rate: 1.0 },
    { defType: 'Bug', rate: 1.0 },
    { defType: 'Rock', rate: 0.5 },
    { defType: 'Ghost', rate: 0.5 },
    { defType: 'Dragon', rate: 1.0 },
    { defType: 'Dark', rate: 1.0 },
    { defType: 'Steel', rate: 0.0 },
    { defType: 'Fairy', rate: 2.0 },
  ]},
  { atkType: 'Ground', rate: [
    { defType: 'Normal', rate: 1.0 },
    { defType: 'Fire', rate: 2.0 },
    { defType: 'Water', rate: 1.0 },
    { defType: 'Electric', rate: 2.0 },
    { defType: 'Grass', rate: 0.5 },
    { defType: 'Ice', rate: 1.0 },
    { defType: 'Fighting', rate: 1.0 },
    { defType: 'Poison', rate: 2.0 },
    { defType: 'Ground', rate:1.0 },
    { defType: 'Flying', rate: 0.0 },
    { defType: 'Psychic', rate: 1.0 },
    { defType: 'Bug', rate: 0.5 },
    { defType: 'Rock', rate: 2.0 },
    { defType: 'Ghost', rate: 1.0 },
    { defType: 'Dragon', rate: 1.0 },
    { defType: 'Dark', rate: 1.0 },
    { defType: 'Steel', rate: 2.0 },
    { defType: 'Fairy', rate: 1.0 },
  ]},
  { atkType: 'Flying', rate: [
    { defType: 'Normal', rate: 1.0 },
    { defType: 'Fire', rate: 1.0 },
    { defType: 'Water', rate: 1.0 },
    { defType: 'Electric', rate: 0.5 },
    { defType: 'Grass', rate: 2.0 },
    { defType: 'Ice', rate: 1.0 },
    { defType: 'Fighting', rate: 2.0 },
    { defType: 'Poison', rate: 1.0 },
    { defType: 'Ground', rate:1.0 },
    { defType: 'Flying', rate: 1.0 },
    { defType: 'Psychic', rate: 1.0 },
    { defType: 'Bug', rate: 2.0 },
    { defType: 'Rock', rate: 0.5 },
    { defType: 'Ghost', rate: 1.0 },
    { defType: 'Dragon', rate: 1.0 },
    { defType: 'Dark', rate: 1.0 },
    { defType: 'Steel', rate: 0.5 },
    { defType: 'Fairy', rate: 1.0 },
  ]},
  { atkType: 'Psychic', rate: [
    { defType: 'Normal', rate: 1.0 },
    { defType: 'Fire', rate: 1.0 },
    { defType: 'Water', rate: 1.0 },
    { defType: 'Electric', rate: 1.0 },
    { defType: 'Grass', rate: 1.0 },
    { defType: 'Ice', rate: 1.0 },
    { defType: 'Fighting', rate: 2.0 },
    { defType: 'Poison', rate: 2.0 },
    { defType: 'Ground', rate:1.0 },
    { defType: 'Flying', rate: 1.0 },
    { defType: 'Psychic', rate: 0.5 },
    { defType: 'Bug', rate: 1.0 },
    { defType: 'Rock', rate: 1.0 },
    { defType: 'Ghost', rate: 1.0 },
    { defType: 'Dragon', rate: 1.0 },
    { defType: 'Dark', rate: 0.0 },
    { defType: 'Steel', rate: 0.5 },
    { defType: 'Fairy', rate: 1.0 },
  ]},
  { atkType: 'Bug', rate: [
    { defType: 'Normal', rate: 1.0 },
    { defType: 'Fire', rate: 0.5 },
    { defType: 'Water', rate: 1.0 },
    { defType: 'Electric', rate: 1.0 },
    { defType: 'Grass', rate: 2.0 },
    { defType: 'Ice', rate: 1.0 },
    { defType: 'Fighting', rate: 0.5 },
    { defType: 'Poison', rate: 0.5 },
    { defType: 'Ground', rate:1.0 },
    { defType: 'Flying', rate: 0.5 },
    { defType: 'Psychic', rate: 2.0 },
    { defType: 'Bug', rate: 1.0 },
    { defType: 'Rock', rate: 1.0 },
    { defType: 'Ghost', rate: 0.5 },
    { defType: 'Dragon', rate: 1.0 },
    { defType: 'Dark', rate: 2.0 },
    { defType: 'Steel', rate: 0.5 },
    { defType: 'Fairy', rate: 0.5 },
  ]},
  { atkType: 'Rock', rate: [
    { defType: 'Normal', rate: 1.0 },
    { defType: 'Fire', rate: 2.0 },
    { defType: 'Water', rate: 1.0 },
    { defType: 'Electric', rate: 1.0 },
    { defType: 'Grass', rate: 1.0 },
    { defType: 'Ice', rate: 2.0 },
    { defType: 'Fighting', rate: 0.5 },
    { defType: 'Poison', rate: 1.0 },
    { defType: 'Ground', rate:0.5 },
    { defType: 'Flying', rate: 2.0 },
    { defType: 'Psychic', rate: 1.0 },
    { defType: 'Bug', rate: 2.0 },
    { defType: 'Rock', rate: 1.0 },
    { defType: 'Ghost', rate: 1.0 },
    { defType: 'Dragon', rate: 1.0 },
    { defType: 'Dark', rate: 1.0 },
    { defType: 'Steel', rate: 0.5 },
    { defType: 'Fairy', rate: 1.0 },
  ]},
  { atkType: 'Ghost', rate: [
    { defType: 'Normal', rate: 0.0 },
    { defType: 'Fire', rate: 1.0 },
    { defType: 'Water', rate: 1.0 },
    { defType: 'Electric', rate: 1.0 },
    { defType: 'Grass', rate: 1.0 },
    { defType: 'Ice', rate: 1.0 },
    { defType: 'Fighting', rate: 1.0 },
    { defType: 'Poison', rate: 1.0 },
    { defType: 'Ground', rate:1.0 },
    { defType: 'Flying', rate: 1.0 },
    { defType: 'Psychic', rate: 2.0 },
    { defType: 'Bug', rate: 1.0 },
    { defType: 'Rock', rate: 1.0 },
    { defType: 'Ghost', rate: 2.0 },
    { defType: 'Dragon', rate: 1.0 },
    { defType: 'Dark', rate: 0.5 },
    { defType: 'Steel', rate: 1.0 },
    { defType: 'Fairy', rate: 1.0 },
  ]},
  { atkType: 'Dragon', rate: [
    { defType: 'Normal', rate: 1.0 },
    { defType: 'Fire', rate: 1.0 },
    { defType: 'Water', rate: 1.0 },
    { defType: 'Electric', rate: 1.0 },
    { defType: 'Grass', rate: 1.0 },
    { defType: 'Ice', rate: 1.0 },
    { defType: 'Fighting', rate: 1.0 },
    { defType: 'Poison', rate: 1.0 },
    { defType: 'Ground', rate:1.0 },
    { defType: 'Flying', rate: 1.0 },
    { defType: 'Psychic', rate: 1.0 },
    { defType: 'Bug', rate: 1.0 },
    { defType: 'Rock', rate: 1.0 },
    { defType: 'Ghost', rate: 1.0 },
    { defType: 'Dragon', rate: 2.0 },
    { defType: 'Dark', rate: 1.0 },
    { defType: 'Steel', rate: 0.5 },
    { defType: 'Fairy', rate: 0.0 },
  ]},
  { atkType: 'Dark', rate: [
    { defType: 'Normal', rate: 1.0 },
    { defType: 'Fire', rate: 1.0 },
    { defType: 'Water', rate: 1.0 },
    { defType: 'Electric', rate: 1.0 },
    { defType: 'Grass', rate: 1.0 },
    { defType: 'Ice', rate: 1.0 },
    { defType: 'Fighting', rate: 0.5 },
    { defType: 'Poison', rate: 1.0 },
    { defType: 'Ground', rate:1.0 },
    { defType: 'Flying', rate: 1.0 },
    { defType: 'Psychic', rate: 2.0 },
    { defType: 'Bug', rate: 1.0 },
    { defType: 'Rock', rate: 1.0 },
    { defType: 'Ghost', rate: 2.0 },
    { defType: 'Dragon', rate: 1.0 },
    { defType: 'Dark', rate: 0.5 },
    { defType: 'Steel', rate: 1.0 },
    { defType: 'Fairy', rate: 0.5 },
  ]},
  { atkType: 'Steel', rate: [
    { defType: 'Normal', rate: 1.0 },
    { defType: 'Fire', rate: 0.5 },
    { defType: 'Water', rate: 0.5 },
    { defType: 'Electric', rate: 0.5 },
    { defType: 'Grass', rate: 1.0 },
    { defType: 'Ice', rate: 2.0 },
    { defType: 'Fighting', rate: 1.0 },
    { defType: 'Poison', rate: 1.0 },
    { defType: 'Ground', rate:1.0 },
    { defType: 'Flying', rate: 1.0 },
    { defType: 'Psychic', rate: 1.0 },
    { defType: 'Bug', rate: 1.0 },
    { defType: 'Rock', rate: 2.0 },
    { defType: 'Ghost', rate: 1.0 },
    { defType: 'Dragon', rate: 1.0 },
    { defType: 'Dark', rate: 1.0 },
    { defType: 'Steel', rate: 0.5 },
    { defType: 'Fairy', rate: 2.0 },
  ]},
  { atkType: 'Fairy', rate: [
    { defType: 'Normal', rate: 1.0 },
    { defType: 'Fire', rate: 0.5 },
    { defType: 'Water', rate: 1.0 },
    { defType: 'Electric', rate: 1.0 },
    { defType: 'Grass', rate: 1.0 },
    { defType: 'Ice', rate: 1.0 },
    { defType: 'Fighting', rate: 2.0 },
    { defType: 'Poison', rate: 0.5 },
    { defType: 'Ground', rate:1.0 },
    { defType: 'Flying', rate: 1.0 },
    { defType: 'Psychic', rate: 1.0 },
    { defType: 'Bug', rate: 1.0 },
    { defType: 'Rock', rate: 1.0 },
    { defType: 'Ghost', rate: 1.0 },
    { defType: 'Dragon', rate: 2.0 },
    { defType: 'Dark', rate: 2.0 },
    { defType: 'Steel', rate: 0.5 },
    { defType: 'Fairy', rate: 1.0 },
  ]},
]


// 音技
const soundMoveList: string[] = [
  'いにしえのうた',
  'いびき',
  'いやしのすず',
  'いやなおと',
  'うたう',
  'うたかたのアリア',
  'エコーボイス',
  'オーバードライブ',
  'おしゃべり',
  'おたけび',
  'きんぞくおん',
  'くさぶえ',
  'さわぐ',
  'スケイルノイズ',
  'すてゼリフ',
  'ソウルビート',
  'チャームボイス',
  'ちょうおんぱ',
  'とおぼえ',
  'ないしょばなし',
  'なきごえ',
  'バークアウト',
  'ハイパーボイス',
  'ばくおんぱ',
  'ぶきみなじゅもん',
  'フレアソング',
  'ブレイジングソウルビート',
  'ほえる',
  'ほろびのうた',
  'むしのさざめき',
  'りんしょう'
]

// 爆発技
const explosionMoveList: string[] = [
  'じばく',
  'だいばくはつ',
  'ビックリヘッド',
  'ミストバースト'
]

// 粉技
const powderMoveList: string[] = [
  'いかりのこな',
  'キノコのほうし',
  'しびれごな',
  'どくのこな',
  'ねむりごな',
  'ふんじん',
  'まほうのこな',
  'わたほうし'
]

// 弾技
const ballMoveList: string[] = [
  'アイスボール',
  'アシッドボム',
  'ウェザーボール',
  'エナジーボール',
  'エレキボール',
  'オクタンほう',
  'かえんだん',
  'かえんボール',
  'かふんだんご',
  'がんせきほう',
  'きあいだま',
  'くちばしキャノン',
  'ジャイロボール',
  'シャドーボール',
  'タネばくだん',
  'タネマシンガン',
  'タマゴばくだん',
  'たまなげ',
  'でんじほう',
  'どろばくだん',
  'はどうだん',
  'ヘドロばくだん',
  'マグネットボム',
  'ミストボール',
  'ロックブラスト'
]

// 一撃必殺技
const oneShotMoveList: string[] = [
  'じわれ',
  'ぜったいれいど',
  'つのドリル',
  'ハサミギロチン'
]

// 踏付技(ちいさくなる状態に対して筆誅となる技)
const stompMoveList: string[] = [
  'ドラゴンダイブ',
  'のしかかり',
  'ハードローラー',
  'ハイパーダーククラッシャー',
  'ヒートスタンプ',
  'ふみつけ',
  'フライングプレス',
  'ヘビーボンバー'
]

// 解氷技
const meltMoveList: string[] = [
  'かえんぐるま',
  'かえんボール',
  'クロスフレイム',
  'スチームバースト',
  'せいなるほのお',
  'ねっさのだいち',
  'ねっとう',
  'ハイドロスチーム',
  'めらめらバーン',
  'もえつきる'
]

// ねむり状態でも使用可能な技
const sleepingMoveList: string[] = [
  'いびき',
  'ねごと'
]

// 重力で使えなくなるわざ
const flyingMoveList: string[] = [
  'はねる',
  'とびげり',
  'とびひざげり',
  'でんじふゆう',
  'そらをとぶ',
  'とびはねる',
  'フリーフォール',
  'テレキネシス',
  'フライングプレス'
]

// かいふくふうじで使えなくなる技
const healMoveList: string[] = [
  'じこさいせい',
  'タマゴうみ',
  'ミルクのみ',
  'なまける',
  'かいふくしれい',
  'ねむる',
  'あさのひざし',
  'こうごうせい',
  'つきのひかり',
  'すなあつめ',
  'はねやすめ',
  'のみこむ',
  'ねがいごと',
  'いやしのねがい',
  'みかづきのまい',
  'いやしのはどう',
  'フラワーヒール',
  'じょうか',
  'ちからをすいとる',
  'かふんだんご'
]

// 捨身技　すてみ
const recklessMoveList: string[] = [
  'アフロブレイク',
  'ウェーブタックル',
  'ウッドハンマー',
  'かかとおとし',
  'じごくぐるま',
  'すてみタックル',
  'とっしん',
  'とびげり',
  'とびひざげり',
  'はめつのひかり',
  'フレアドライブ',
  'ブレイブバード',
  'ボルテッカー',
  'もろはのずつき',
  'ワイルドボルト'
]

// 拳技　てつのこぶし
const ironFistMoveList: string[] = [
  'アームハンマー',
  'アイスハンマー',
  'あんこくきょうだ',
  'かみなりパンチ',
  'きあいパンチ',
  'グロウパンチ',
  'コメットパンチ',
  'ジェットパンチ',
  'シャドーパンチ',
  'すいりゅうれんだ',
  'スカイアッパー',
  'ダブルパンツァー',
  'ドレインパンチ',
  'ばくれつパンチ',
  'バレットパンチ',
  'ピヨピヨパンチ',
  'ぶちかまし',
  'プラズマフィスト',
  'ふんどのこぶし',
  'ほのおのパンチ',
  'マッハパンチ',
  'メガトンパンチ',
  'れいとうパンチ',
  'れんぞくパンチ'
]

// 噛付技　がんじょうあご
const biteMoveList: string[] = [
  'エラがみ',
  'かみくだく',
  'かみつく',
  'かみなりのキバ',
  'くらいつく',
  'こおりのキバ',
  'サイコファング',
  'どくどくのキバ',
  'ひっさつまえば',
  'ほのおのキバ'
]

// 波動技　メガランチャー
const waveMoveList: string[] = [
  'あくのはどう',
  'いやしのはどう',
  'こんげんのはどう',
  'だいちのはどう',
  'はどうだん',
  'みずのはどう',
  'りゅうのはどう'
]

// 吸収技
const absorbingMoveList = [
  { name: 'いきいきバブル', rate: 0.5 },
  { name: 'ウッドホーン', rate: 0.5 },
  { name: 'ギガドレイン', rate: 0.5 },
  { name: 'きゅうけつ', rate: 0.5 },
  { name: 'すいとる', rate: 0.5 },
  { name: 'デスウィング', rate: 0.75 },
  { name: 'ドレインキッス', rate: 0.75 },
  { name: 'ドレインパンチ', rate: 0.5 },
  { name: 'パラボラチャージ', rate: 0.5 },
  { name: 'むねんのつるぎ', rate: 0.5 },
  { name: 'メガドレイン', rate: 0.5 },
  { name: 'やどりぎのタネ', rate: 0.5 },
  { name: 'ゆめくい', rate: 0.5 },
]

// 風技
const windMoveList: string[] = [
  'エアカッター',
  'おいかぜ',
  'かぜおこし',
  'かみなりあらし',
  'こがらしあらし',
  'こごえるかぜ',
  'すなあらし',
  'たつまき',
  'ねっさのあらし',
  'ねっぷう',
  'はなふぶき',
  'はるのあらし',
  'ふきとばし',
  'ふぶき',
  'ぼうふう',
  'ようせいのかぜ'
]

// 縛技
const bindMoveList = [
  'うずしお',
  'からではさむ',
  'キョダイサジン',
  'キョダイヒャッカ',
  'サンダープリズン',
  'しめつける',
  'すなじごく',
  'トラバサミ',
  'ほのおのうず',
  'まきつく',
  'マグマストーム',
  'まとわりつく'
]

// タイプ変化技
const changeTypeMoveList = [
  'ウェザーボール',
  'オーラぐるま',
  'さばきのつぶて',
  'しぜんのめぐみ',
  'だいちのはどう',
  'テクノバスター',
  'テラバースト',
  'マルチアタック',
  'めざめるダンス',
  'めざめるパワー',
  'レイジングブル'
]

// 特性の変更可否
// https://wiki.xn--rckteqa2e.com/wiki/%E3%81%A8%E3%81%8F%E3%81%9B%E3%81%84
const changeAbilityTable: changeAbilityType[] = [
  { name: 'ARシステム', exchange: 1, overwrite: 1, noAbility: 1, neutral: 1, copy: 1, copied: 1, transform: 2 },
  { name: 'アイスフェイス', exchange: 1, overwrite: 1, noAbility: 1, neutral: 1, copy: 1, copied: 1, transform: 2 },
  { name: 'イリュージョン', exchange: 1, overwrite: 0, noAbility: 0, neutral: 0, copy: 1, copied: 1, transform: 2 },
  { name: 'うのミサイル', exchange: 1, overwrite: 1, noAbility: 1, neutral: 1, copy: 1, copied: 1, transform: 2 },
  { name: 'かがくのちから', exchange: 0, overwrite: 0, noAbility: 0, neutral: 0, copy: 1, copied: 1, transform: 0 },
  { name: 'かがくへんかガス', exchange: 1, overwrite: 0, noAbility: 0, neutral: 1, copy: 1, copied: 1, transform: 2 },
  { name: 'かわりもの', exchange: 2, overwrite: 0, noAbility: 0, neutral: 0, copy: 1, copied: 1, transform: 2 },
  { name: 'きずなへんげ', exchange: 1, overwrite: 1, noAbility: 1, neutral: 4, copy: 1, copied: 1, transform: 2 },
  { name: 'ぎょぐん', exchange: 1, overwrite: 1, noAbility: 1, neutral: 1, copy: 1, copied: 1, transform: 2 },
  { name: 'クォークチャージ', exchange: 1, overwrite: 1, noAbility: 1, neutral: 4, copy: 1, copied: 1, transform: 2 },
  { name: 'こだいかっせい', exchange: 1, overwrite: 1, noAbility: 1, neutral: 4, copy: 1, copied: 1, transform: 2 },
  { name: 'しれいとう', exchange: 1, overwrite: 1, noAbility: 1, neutral: 4, copy: 1, copied: 1, transform: 2 },
  { name: 'じんばいったい', exchange: 1, overwrite: 1, noAbility: 1, neutral: 1, copy: 1, copied: 1, transform: 0 },
  { name: 'スワームチェンジ', exchange: 1, overwrite: 1, noAbility: 1, neutral: 1, copy: 1, copied: 1, transform: 2 },
  { name: 'ぜったいねむり', exchange: 1, overwrite: 1, noAbility: 1, neutral: 4, copy: 1, copied: 1, transform: 0 },
  { name: 'ダルマモード', exchange: 1, overwrite: 1, noAbility: 1, neutral: 1, copy: 1, copied: 1, transform: 2 },
  { name: 'てんきや', exchange: 2, overwrite: 0, noAbility: 0, neutral: 0, copy: 1, copied: 1, transform: 2 },
  { name: 'トレース', exchange: 0, overwrite: 0, noAbility: 0, neutral: 0, copy: 1, copied: 1, transform: 0 },
  { name: 'なまけ', exchange: 0, overwrite: 1, noAbility: 0, neutral: 0, copy: 0, copied: 0, transform: 0 },
  { name: 'ばけのかわ', exchange: 1, overwrite: 1, noAbility: 1, neutral: 1, copy: 1, copied: 1, transform: 2 },
  { name: 'バトルスイッチ', exchange: 1, overwrite: 1, noAbility: 1, neutral: 1, copy: 1, copied: 1, transform: 2 },
  { name: 'ハドロンエンジン', exchange: 1, overwrite: 1, noAbility: 1, neutral: 4, copy: 1, copied: 1, transform: 2 },
  { name: 'はらぺこスイッチ', exchange: 1, overwrite: 0, noAbility: 0, neutral: 0, copy: 1, copied: 1, transform: 2 },
  { name: 'ひひいろのこどう', exchange: 1, overwrite: 1, noAbility: 1, neutral: 4, copy: 1, copied: 1, transform: 2 },
  { name: 'ふしぎなまもり', exchange: 1, overwrite: 0, noAbility: 0, neutral: 0, copy: 0, copied: 1, transform: 0 },
  { name: 'フラワーギフト', exchange: 2, overwrite: 0, noAbility: 0, neutral: 0, copy: 1, copied: 1, transform: 2 },
  { name: 'マイティチェンジ', exchange: 1, overwrite: 1, noAbility: 1, neutral: 4, copy: 1, copied: 1, transform: 2 },
  { name: 'マルチタイプ', exchange: 1, overwrite: 1, noAbility: 1, neutral: 4, copy: 1, copied: 1, transform: 2 },
  { name: 'リミットシールド', exchange: 1, overwrite: 1, noAbility: 1, neutral: 4, copy: 1, copied: 1, transform: 2 },
  { name: 'レシーバー', exchange: 0, overwrite: 0, noAbility: 0, neutral: 0, copy: 1, copied: 1, transform: 2 },
]


// プレート
const plateTable: ItemForType[] = [
  { name: 'あおぞらプレート', type: 'Flying' },
  { name: 'いかずちプレート', type: 'Electric' },
  { name: 'がんせきプレート', type: 'Rock' },
  { name: 'こうてつプレート', type: 'Steel' },
  { name: 'こぶしのプレート', type: 'Fighting' },
  { name: 'こわもてプレート', type: 'Dark' },
  { name: 'しずくプレート', type: 'Water' },
  { name: 'せいれいプレート', type: 'Fairy' },
  { name: 'だいちのプレート', type: 'Ground' },
  { name: 'たまむしプレート', type: 'Bug' },
  { name: 'つららのプレート', type: 'Ice' },
  { name: 'ひのたまプレート', type: 'Fire' },
  { name: 'ふしぎのプレート', type: 'Psychic' },
  { name: 'みどりのプレート', type: 'Grass' },
  { name: 'もうどくプレート', type: 'Poison' },
  { name: 'もののけプレート', type: 'Ghost' },
  { name: 'りゅうのプレート', type: 'Dragon' }
]

// ジュエル
const gemTable: ItemForType[] = [
  { name: 'あくのジュエル', type: 'Dark' },
  { name: 'いわのジュエル', type: 'Rock' },
  { name: 'エスパージュエル', type: 'Psychic' },
  { name: 'かくとうジュエル', type: 'Fighting' },
  { name: 'くさのジュエル', type: 'Grass' },
  { name: 'ゴーストジュエル', type: 'Ghost' },
  { name: 'こおりのジュエル', type: 'Ice' },
  { name: 'じめんのジュエル', type: 'Ground' },
  { name: 'でんきのジュエル', type: 'Electric' },
  { name: 'どくのジュエル', type: 'Poison' },
  { name: 'ドラゴンジュエル', type: 'Dragon' },
  { name: 'ノーマルジュエル', type: 'Normal' },
  { name: 'はがねのジュエル', type: 'Steel' },
  { name: 'ひこうのジュエル', type: 'Flying' },
  { name: 'ようせいジュエル', type: 'Fairy' },
  { name: 'ほのおのジュエル', type: 'Fire' },
  { name: 'みずのジュエル', type: 'Water' },
  { name: 'むしのジュエル', type: 'Bug' }
]

// メモリ
const memoryTable: ItemForType[] = [
  { name: 'アイスメモリ', type: 'Ice' },
  { name: 'ウオーターメモリ', type: 'Water' },
  { name: 'エレクトロメモリ', type: 'Electric' },
  { name: 'グラウンドメモリ', type: 'Ground' },
  { name: 'グラスメモリ', type: 'Grass' },
  { name: 'ゴーストメモリ', type: 'Ghost' },
  { name: 'サイキックメモリ', type: 'Psychic' },
  { name: 'スチールメモリ', type: 'Steel' },
  { name: 'ダークメモリ', type: 'Dark' },
  { name: 'ドラゴンメモリ', type: 'Dragon' },
  { name: 'バグメモリ', type: 'Bug' },
  { name: 'ファイトメモリ', type: 'Fighting' },
  { name: 'ファイヤーメモリ', type: 'Fire' },
  { name: 'フェアリーメモリ', type: 'Fairy' },
  { name: 'フライングメモリ', type: 'Flying' },
  { name: 'ポイズンメモリ', type: 'Poison' },
  { name: 'ロックメモリ', type: 'Rock' }
]

// カセット
const driveTable: ItemForType[] = [
  { name: 'アクアカセット', type: 'Water' },
  { name: 'イナズマカセット', type: 'Electric' },
  { name: 'フリーズカセット', type: 'Ice' },
  { name: 'ブレイズカセット', type: 'Fire' }
]

// シルクのスカーフ、おこう
const incenseTable: ItemForType[] = [
  { name: 'あやしいおこう', type: 'Psychic' },
  { name: 'うしおのおこう', type: 'Water' },
  { name: 'おはなのおこう', type: 'Grass' },
  { name: 'かたいいし', type: 'Rock' },
  { name: 'がんせきおこう', type: 'Rock' },
  { name: 'きせきのタネ', type: 'Grass' },
  { name: 'ぎんのこな', type: 'Bug' },
  { name: 'くろいメガネ', type: 'Dark' },
  { name: 'くろおび', type: 'Fighting' },
  { name: 'さざなみのおこう', type: 'Water' },
  { name: 'じしゃく', type: 'Electric' },
  { name: 'シルクのスカーフ', type: 'Normal' },
  { name: 'しんぴのしずく', type: 'Water' },
  { name: 'するどいくちばし', type: 'Flying' },
  { name: 'どくバリ', type: 'Poison' },
  { name: 'とけないこおり', type: 'Ice' },
  { name: 'のろいのおふだ', type: 'Ghost' },
  { name: 'まがったスプーン', type: 'Psychic' },
  { name: 'メタルコート', type: 'Steel' },
  { name: 'もくたん', type: 'Fire' },
  { name: 'やわらかいすな', type: 'Ground' },
  { name: 'りゅうのキバ', type: 'Dragon' }
]

// Zクリスタル
const zCrystalTable = [
  { name: 'アクZ', type: 'DARK', Zmove: 'ブラックホールイクリプス', move: '', pokemon: '' },
  { name: 'アシレーヌZ', type: 'WATER', Zmove: 'わだつみのシンフォニア', move: 'うたかたのアリア', pokemon: 'アシレーヌ' },
  { name: 'アロライZ', type: 'ELECTRIC', Zmove: 'ライトニングサーフライド', move: '10まんボルト', pokemon: 'ライチュウ(アローラ)' },
  { name: 'イーブイZ', type: 'NORMAL', Zmove: 'ナインエボルブースト', move: 'とっておき', pokemon: 'イーブイ' },
  { name: 'イワZ', type: 'ROCK', Zmove: 'ワールズエンドフォール', move: '', pokemon: '' },
  { name: 'ウルトラネクロZ', type: 'PSYCHIC', Zmove: 'てんこがすめつぼうのひかり', move: 'フォトンゲイザー', pokemon: 'ネクロズマ(ウルトラ)' },
  { name: 'エスパーZ', type: 'PSYCHIC', Zmove: 'マキシマムサイブレイカー', move: '', pokemon: '' },
  { name: 'ガオガエンZ', type: 'DARK', Zmove: 'ハイパーダーククラッシャー', move: 'DDラリアット', pokemon: 'ガオガエン' },
  { name: 'カクトウZ', type: 'FIGHTING', Zmove: 'ぜんりょくむそうげきれつけん', move: '', pokemon: '' },
  { name: 'カビゴンZ', type: 'NORMAL', Zmove: 'ほんきをだすこうげき', move: 'ギガインパクト', pokemon: 'カビゴン' },
  { name: 'カプZ', type: 'FAIRY', Zmove: 'ガーディアン・デ・アローラ', move: 'しぜんのいかり', pokemon: 'カプ・コケコ' },
  { name: 'カプZ', type: 'FAIRY', Zmove: 'ガーディアン・デ・アローラ', move: 'しぜんのいかり', pokemon: 'カプ・テテフ' },
  { name: 'カプZ', type: 'FAIRY', Zmove: 'ガーディアン・デ・アローラ', move: 'しぜんのいかり', pokemon: 'カプ・ブルル' },
  { name: 'カプZ', type: 'FAIRY', Zmove: 'ガーディアン・デ・アローラ', move: 'しぜんのいかり', pokemon: 'カプ・レヒレ' },
  { name: 'クサZ', type: 'GRASS', Zmove: 'ブルームシャインエクストラ', move: '', pokemon: '' },
  { name: 'ゴーストZ', type: 'GHOST', Zmove: 'むげんあんやへのいざない', move: '', pokemon: '' },
  { name: 'コオリZ', type: 'ICE', Zmove: 'レイジングジオフリーズ', move: '', pokemon: '' },
  { name: 'サトピカZ', type: '', Zmove: '', move: '', pokemon: '' },
  { name: 'ジメンZ', type: 'GROUND', Zmove: 'ライジングランドオーバー', move: '', pokemon: '' },
  { name: 'ジャラランガZ', type: 'DRAGON', Zmove: 'ブレイジングソウルビート', move: 'スケイルノイズ', pokemon: 'ジャラランガ' },
  { name: 'ジュナイパーZ', type: 'GHOST', Zmove: 'シャドーアローズストライク', move: 'かげぬい', pokemon: 'ジュナイパー' },
  { name: 'ソルガレオZ', type: 'STEEL', Zmove: 'サンシャインスマッシャー', move: 'メテオドライブ', pokemon: 'ソルガレオ' },
  { name: 'ソルガレオZ', type: 'STEEL', Zmove: 'サンシャインスマッシャー', move: 'メテオドライブ', pokemon: 'ネクロズマ(日食)' },
  { name: 'デンキZ', type: 'ELECTRIC', Zmove: 'スパーキングギガボルト', move: '', pokemon: '' },
  { name: 'ドクZ', type: 'POISON', Zmove: 'アシッドポイズンデリート', move: '', pokemon: '' },
  { name: 'ドラゴンZ', type: 'DRAGON', Zmove: 'アルティメットドラゴンバーン', move: '', pokemon: '' },
  { name: 'ノーマルZ', type: 'NORMAL', Zmove: 'ウルトラダッシュアタック', move: '', pokemon: '' },
  { name: 'ハガネZ', type: 'STEEL', Zmove: 'ちょうぜつらせんれんげき', move: '', pokemon: '' },
  { name: 'ピカチュウZ', type: 'ELECTRIC', Zmove: 'ひっさつのピカチュート', move: 'ボルテッカー', pokemon: 'ピカチュウ' },
  { name: 'ヒコウZ', type: 'FLYING', Zmove: 'ファイナルダイブクラッシュ', move: '', pokemon: '' },
  { name: 'フェアリーZ', type: 'FAIRY', Zmove: 'ラブリースターインパクト', move: '', pokemon: '' },
  { name: 'ホノオZ', type: 'FIRE', Zmove: 'ダイナミックフルフレイム', move: '', pokemon: '' },
  { name: 'マーシャドーZ', type: 'GHOST', Zmove: 'しちせいだっこんたい', move: 'シャドースチール', pokemon: 'マーシャドー' },
  { name: 'ミズZ', type: 'WATER', Zmove: 'スーパーアクアトルネード', move: '', pokemon: '' },
  { name: 'ミミッキュZ', type: 'FAIRY', Zmove: 'ぽかぽかフレンドタイム', move: 'じゃれつく', pokemon: 'ミミッキュ' },
  { name: 'ミュウZ', type: 'PSYCHIC', Zmove: 'オリジンズスーパーノヴァ', move: 'サイコキネシス', pokemon: 'ミュウ' },
  { name: 'ムシZ', type: 'BUG', Zmove: 'ぜったいほしょくかいてんざん', move: '', pokemon: '' },
  { name: 'ルガルガンZ', type: 'ROCK', Zmove: 'ラジアルエッジストーム', move: 'ストーンエッジ', pokemon: 'ルガルガン(真昼)' },
  { name: 'ルガルガンZ', type: 'ROCK', Zmove: 'ラジアルエッジストーム', move: 'ストーンエッジ', pokemon: 'ルガルガン(真夜中)' },
  { name: 'ルガルガンZ', type: 'ROCK', Zmove: 'ラジアルエッジストーム', move: 'ストーンエッジ', pokemon: 'ルガルガン(黄昏)' },
  { name: 'ルナアーラZ', type: 'GHOST', Zmove: 'ムーンライトブラスター', move: 'シャドーレイ', pokemon: 'ルナアーラ' },
  { name: 'ルナアーラZ', type: 'GHOST', Zmove: 'ムーンライトブラスター', move: 'シャドーレイ', pokemon: 'ネクロズマ(月食)' }
]

// メガストーン
const megaStoneTable = [
  { name: 'アブソルナイト', pokemon: 'アブソル', mega: 'メガアブソル' },
  { name: 'エルレイドナイト', pokemon: 'エルレイド', mega: 'メガエルレイド' },
  { name: 'オニゴーリナイト', pokemon: 'オニゴーリ', mega: 'メガオニゴーリ' },
  { name: 'カイロスナイト', pokemon: 'カイロス', mega: 'メガカイロス' },
  { name: 'ガブリアスナイト', pokemon: 'ガブリアス', mega: 'メガガブリアス' },
  { name: 'カメックスナイト', pokemon: 'カメックス', mega: 'メガカメックス' },
  { name: 'ガルーラナイト', pokemon: 'ガルーラ', mega: 'メガガルーラ' },
  { name: 'ギャラドスナイト', pokemon: 'ギャラドス', mega: 'メガギャラドス' },
  { name: 'クチートナイト', pokemon: 'クチート', mega: 'メガクチート' },
  { name: 'ゲンガナイト', pokemon: 'ゲンガー', mega: 'メガゲンガー' },
  { name: 'サーナイトナイト', pokemon: 'サーナイト', mega: 'メガサーナイト' },
  { name: 'サメハダナイト', pokemon: 'サメハダー', mega: 'メガサメハダー' },
  { name: 'ジュカインナイト', pokemon: 'ジュカイン', mega: 'メガジュカイン' },
  { name: 'ジュペッタナイト', pokemon: 'ジュペッタ', mega: 'メガジュペッタ' },
  { name: 'スピアナイト', pokemon: 'スピアー', mega: 'メガスピアー' },
  { name: 'タブンネナイト', pokemon: 'タブンネ', mega: 'メガタブンネ' },
  { name: 'チャーレムナイト', pokemon: 'チャーレム', mega: 'メガチャーレム' },
  { name: 'チルタリスナイト', pokemon: 'チルタリス', mega: 'メガチルタリス' },
  { name: 'ディアンシナイト', pokemon: 'ディアンシー', mega: 'メガディアンシー' },
  { name: 'デンリュウナイト', pokemon: 'デンリュウ', mega: 'メガデンリュウ' },
  { name: 'ハガネールナイト', pokemon: 'ハガネール', mega: 'メガハガネール' },
  { name: 'バクーダナイト', pokemon: 'バクーダ', mega: 'メガバクーダ' },
  { name: 'バシャーモナイト', pokemon: 'バシャーモ', mega: 'メガバシャーモ' },
  { name: 'ハッサムナイト', pokemon: 'ハッサム', mega: 'メガハッサム' },
  { name: 'バンギラスナイト', pokemon: 'バンギラス', mega: 'メガバンギラス' },
  { name: 'ピジョットナイト', pokemon: 'ピジョット', mega: 'メガピジョット' },
  { name: 'フーディナイト', pokemon: 'フーディン', mega: 'メガフーディン' },
  { name: 'フシギバナイト', pokemon: 'フシギバナ', mega: 'メガフシギバナ' },
  { name: 'プテラナイト', pokemon: 'プテラ', mega: 'メガプテラ' },
  { name: 'ヘラクロスナイト', pokemon: 'ヘラクロス', mega: 'メガヘラクロス' },
  { name: 'ヘルガナイト', pokemon: 'ヘルガー', mega: 'メガヘルガー' },
  { name: 'ボーマンダナイト', pokemon: 'ボーマンダ', mega: 'メガボーマンダ' },
  { name: 'ボスゴドラナイト', pokemon: 'ボスゴドラ', mega: 'メガボスゴドラ' },
  { name: 'ミミロップナイト', pokemon: 'ミミロップ', mega: 'メガミミロップ' },
  { name: 'ミュウツナイトX', pokemon: 'ミュウツー', mega: 'メガミュウーツーX' },
  { name: 'ミュウツナイトY', pokemon: 'ミュウツー', mega: 'メガミュウツーY' },
  { name: 'メタグロスナイト', pokemon: 'メタグロス', mega: 'メガメタグロス' },
  { name: 'ヤドランナイト', pokemon: 'ヤドラン', mega: 'メガヤドラン' },
  { name: 'ヤミラミナイト', pokemon: 'ヤミラミ', mega: 'メガヤミラミ' },
  { name: 'ユキノオナイト', pokemon: 'ユキノオー', mega: 'メガユキノオー' },
  { name: 'ライボルトナイト', pokemon: 'ライボルト', mega: 'メガライボルト' },
  { name: 'ラグラージナイト', pokemon: 'ラグラージ', mega: 'メガラグラージ' },
  { name: 'ラティアスナイト', pokemon: 'ラティアス', mega: 'メガラティアス' },
  { name: 'ラティオスナイト', pokemon: 'ラティオス', mega: 'メガラティオス' },
  { name: 'リザードナイトX', pokemon: 'リザードンX', mega: 'メガリザードンX' },
  { name: 'リザードナイトY', pokemon: 'リザードンY', mega: 'メガリザードンY' },
  { name: 'ルカリオナイト', pokemon: 'ルカリオ', mega: 'メガルカリオ' },
]

// 追加効果のある技（対象のランクを変化させる）
const additionalEffectTargetRank: AdditionalEffectRank[] = [
  { name: 'オーロラビーム', rate: 10, change: { attack: -1, defense: 0, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'じゃれつく', rate: 10, change: { attack: -1, defense: 0, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'はるのあらし', rate: 30, change: { attack: -1, defense: 0, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'うらみつらみ', rate: 100, change: { attack: -1, defense: 0, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'とびかかる', rate: 100, change: { attack: -1, defense: 0, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'トロピカルキック', rate: 100, change: { attack: -1, defense: 0, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'ひやみず', rate: 100, change: { attack: -1, defense: 0, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'ワイドブレイカー', rate: 100, change: { attack: -1, defense: 0, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'アクアブレイク', rate: 20, change: { attack: 0, defense: -1, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'かみくだく', rate: 20, change: { attack: 0, defense: -1, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'シャドーボーン', rate: 20, change: { attack: 0, defense: -1, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'アイアンテール', rate: 30, change: { attack: 0, defense: -1, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: '3ぼんのや', rate: 50, change: { attack: 0, defense: -1, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'いわくだき', rate: 50, change: { attack: 0, defense: -1, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'シェルブレード', rate: 50, change: { attack: 0, defense: -1, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'ブレイククロー', rate: 50, change: { attack: 0, defense: -1, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'Gのちから', rate: 100, change: { attack: 0, defense: -1, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'ほのおのムチ', rate: 100, change: { attack: 0, defense: -1, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'らいめいげり', rate: 100, change: { attack: 0, defense: -1, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'ムーンフォース', rate: 30, change: { attack: 0, defense: 0, specialAttack: -1, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'ミストボール', rate: 50, change: { attack: 0, defense: 0, specialAttack: -1, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'ソウルクラッシュ', rate: 100, change: { attack: 0, defense: 0, specialAttack: -1, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'バークアウト', rate: 100, change: { attack: 0, defense: 0, specialAttack: -1, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'はいよるいちげき', rate: 100, change: { attack: 0, defense: 0, specialAttack: -1, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'マジカルフレイム', rate: 100, change: { attack: 0, defense: 0, specialAttack: -1, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'むしのていこう', rate: 100, change: { attack: 0, defense: 0, specialAttack: -1, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'エナジーボール', rate: 10, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: -1, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'きあいだま', rate: 10, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: -1, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'サイコキネシス', rate: 10, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: -1, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'シードフレア', rate: 40, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: -2, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'シャドーボール', rate: 20, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: -1, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'だいちのちから', rate: 10, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: -1, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'むしのさざめき', rate: 10, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: -1, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'ようかいえき', rate: 10, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: -1, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'ラスターカノン', rate: 10, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: -1, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'ラスターパージ', rate: 50, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: -1, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'アシッドボム', rate: 100, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: -2, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'りんごさん', rate: 100, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: -1, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'ルミナコリジョン', rate: 100, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: -2, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'あわ', rate: 10, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: -1, accuracy: 0, evasion: 0 } },
  { name: 'エレキネット', rate: 100, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: -1, accuracy: 0, evasion: 0 } },
  { name: 'からみつく', rate: 10, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: -1, accuracy: 0, evasion: 0 } },
  { name: 'がんせきふうじ', rate: 100, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: -1, accuracy: 0, evasion: 0 } },
  { name: 'こがらしあらし', rate: 30, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: -1, accuracy: 0, evasion: 0 } },
  { name: 'こごえるかぜ', rate: 100, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: -1, accuracy: 0, evasion: 0 } },
  { name: 'こごえるせかい', rate: 100, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: -1, accuracy: 0, evasion: 0 } },
  { name: 'じならし', rate: 100, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: -1, accuracy: 0, evasion: 0 } },
  { name: 'とびつく', rate: 100, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: -1, accuracy: 0, evasion: 0 } },
  { name: 'ドラムアタック', rate: 100, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: -1, accuracy: 0, evasion: 0 } },
  { name: 'バブルこうせん', rate: 10, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: -1, accuracy: 0, evasion: 0 } },
  { name: 'マッドショット', rate: 100, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: -1, accuracy: 0, evasion: 0 } },
  { name: 'ローキック', rate: 100, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: -1, accuracy: 0, evasion: 0 } },
  { name: 'オクタンほう', rate: 50, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: -1, evasion: 0 } },
  { name: 'グラスミキサー', rate: 50, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: -1, evasion: 0 } },
  { name: 'だくりゅう', rate: 30, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: -1, evasion: 0 } },
  { name: 'どろかけ', rate: 100, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: -1, evasion: 0 } },
  { name: 'どろばくだん', rate: 30, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: -1, evasion: 0 } },
  { name: 'ナイトバースト', rate: 40, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: -1, evasion: 0 } },
  { name: 'ミラーショット', rate: 30, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: -1, evasion: 0 } },
]

// 追加効果のある技（自分のランクを変化させる）
const additionalEffectMyRank: AdditionalEffectRank[] = [
  { name: 'メタルクロー', rate: 10, change: { attack: 1, defense: 0, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'コメットパンチ', rate: 20, change: { attack: 1, defense: 0, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'グロウパンチ', rate: 100, change: { attack: 1, defense: 0, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'はがねのつばさ', rate: 10, change: { attack: 0, defense: 1, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'ダイヤストーム', rate: 50, change: { attack: 0, defense: 2, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'バリアーラッシュ', rate: 100, change: { attack: 0, defense: 1, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'ほのおのまい', rate: 50, change: { attack: 0, defense: 0, specialAttack: 1, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'チャージビーム', rate: 70, change: { attack: 0, defense: 0, specialAttack: 1, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'しんぴのちから', rate: 100, change: { attack: 0, defense: 0, specialAttack: 1, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'フレアソング', rate: 100, change: { attack: 0, defense: 0, specialAttack: 1, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'アクアステップ', rate: 100, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: 1, accuracy: 0, evasion: 0 } },
  { name: 'オーラウイング', rate: 100, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: 1, accuracy: 0, evasion: 0 } },
  { name: 'オーラぐるま', rate: 100, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: 1, accuracy: 0, evasion: 0 } },
  { name: 'くさわけ', rate: 100, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: 1, accuracy: 0, evasion: 0 } },
  { name: 'こうそくスピン', rate: 100, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: 1, accuracy: 0, evasion: 0 } },
  { name: 'ニトロチャージ', rate: 100, change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: 1, accuracy: 0, evasion: 0 } },
  { name: 'あやしいかぜ', rate: 10, change: { attack: 1, defense: 1, specialAttack: 1, specialDefense: 1, speed: 1, accuracy: 0, evasion: 0 } },
  { name: 'げんしのちから', rate: 10, change: { attack: 1, defense: 1, specialAttack: 1, specialDefense: 1, speed: 1, accuracy: 0, evasion: 0 } },
  { name: 'ぎんいろのかぜ', rate: 10, change: { attack: 1, defense: 1, specialAttack: 1, specialDefense: 1, speed: 1, accuracy: 0, evasion: 0 } },
  { name: 'ブレイジングソウルビート', rate: 100, change: { attack: 1, defense: 1, specialAttack: 1, specialDefense: 1, speed: 1, accuracy: 0, evasion: 0 } },
]

// 追加効果のある技（対象をひるみ状態にさせる）
const additionalEffectFlinch = [
  { name: '3ぼんのや', rate: 30 },
  { name: 'アイアンヘッド', rate: 30 },
  { name: 'あくのはどう', rate: 20 },
  { name: 'いびき', rate: 30 },
  { name: 'いわなだれ', rate: 30 },
  { name: 'エアスラッシュ', rate: 30 },
  { name: 'おどろかす', rate: 30 },
  { name: 'かみつく', rate: 30 },
  { name: 'かみなりのキバ', rate: 10 },
  { name: 'けたぐり', rate: 30 },
  { name: 'こおりのキバ', rate: 10 },
  { name: 'ゴッドバード', rate: 30 },
  { name: 'しねんのずつき', rate: 20 },
  { name: 'じんつうりき', rate: 10 },
  { name: 'ずつき', rate: 30 },
  { name: 'たきのぼり', rate: 20 },
  { name: 'たつまき', rate: 20 },
  { name: 'ダブルパンツァー', rate: 30 },
  { name: 'つららおとし', rate: 30 },
  { name: 'ドラゴンダイブ', rate: 20 },
  { name: 'ニードルアーム', rate: 30 },
  { name: 'ねこだまし', rate: 100 },
  { name: 'ハートスタンプ', rate: 30 },
  { name: 'ハードローラー', rate: 30 },
  { name: 'ひっさつまえば', rate: 10 },
  { name: 'ひょうざんおろし', rate: 30 },
  { name: 'びりびりちくちく', rate: 30 },
  { name: 'ふみつけ', rate: 30 },
  { name: 'ふわふわフォール', rate: 30 },
  { name: 'ホネこんぼう', rate: 10 },
  { name: 'ほのおのキバ', rate: 10 },
  { name: 'まわしげり', rate: 30 },
  { name: 'もえあがるいかり', rate: 20 },
]

// 追加効果のある技（対象を状態異常にさせる）
const additionalEffectAilment = [
  { name: '10まんボルト', rate: 10, ailment: 'まひ' },
  { name: 'かみなり', rate: 30, ailment: 'まひ' },
  { name: 'かみなりあらし', rate: 20, ailment: 'まひ' },
  { name: 'かみなりのキバ', rate: 10, ailment: 'まひ' },
  { name: 'かみなりパンチ', rate: 10, ailment: 'まひ' },
  { name: 'ざぶざぶサーフ', rate: 30, ailment: 'まひ' },
  { name: 'スパーク', rate: 30, ailment: 'まひ' },
  { name: 'でんきショック', rate: 10, ailment: 'まひ' },
  { name: 'でんじほう', rate: 100, ailment: 'まひ' },
  { name: 'とびはねる', rate: 30, ailment: 'まひ' },
  { name: 'のしかかり', rate: 30, ailment: 'まひ' },
  { name: 'はっけい', rate: 30, ailment: 'まひ' },
  { name: 'びりびりエレキ', rate: 100, ailment: 'まひ' },
  { name: 'ファイトアクセル', rate: 30, ailment: 'まひ' },
  { name: 'フリーズボルト', rate: 30, ailment: 'まひ' },
  { name: 'ほうでん', rate: 30, ailment: 'まひ' },
  { name: 'ほっぺすりすり', rate: 100, ailment: 'まひ' },
  { name: 'ボルテッカー', rate: 10, ailment: 'まひ' },
  { name: 'らいげき', rate: 20, ailment: 'まひ' },
  { name: 'ライトニングサーフライド', rate: 100, ailment: 'まひ' },
  { name: 'りゅうのいぶき', rate: 30, ailment: 'まひ' },
  { name: 'いてつくしせん', rate: 10, ailment: 'こおり' },
  { name: 'こおりのキバ', rate: 10, ailment: 'こおり' },
  { name: 'こなゆき', rate: 10, ailment: 'こおり' },
  { name: 'ふぶき', rate: 10, ailment: 'こおり' },
  { name: 'フリーズドライ', rate: 10, ailment: 'こおり' },
  { name: 'れいとうパンチ', rate: 10, ailment: 'こおり' },
  { name: 'れいとうビーム', rate: 10, ailment: 'こおり' },
  { name: 'かえんだん', rate: 30, ailment: 'やけど' },
  { name: 'かえんほうしゃ', rate: 10, ailment: 'やけど' },
  { name: 'かえんボール', rate: 10, ailment: 'やけど' },
  { name: 'コールドフレア', rate: 30, ailment: 'やけど' },
  { name: 'スチームバースト', rate: 30, ailment: 'やけど' },
  { name: 'せいなるほのお', rate: 50, ailment: 'やけど' },
  { name: 'だいもんじ', rate: 30, ailment: 'やけど' },
  { name: 'ねっさのあらし', rate: 20, ailment: 'やけど' },
  { name: 'ねっさのだいち', rate: 30, ailment: 'やけど' },
  { name: 'ねっとう', rate: 30, ailment: 'やけど' },
  { name: 'ねっぷう', rate: 10, ailment: 'やけど' },
  { name: 'バーンアクセル', rate: 30, ailment: 'やけど' },
  { name: 'ひのこ', rate: 10, ailment: 'やけど' },
  { name: 'ひゃっきやこう', rate: 30, ailment: 'やけど' },
  { name: 'ブレイズキック', rate: 10, ailment: 'やけど' },
  { name: 'ふんえん', rate: 30, ailment: 'やけど' },
  { name: 'ほのおのキバ', rate: 10, ailment: 'やけど' },
  { name: 'ほのおのパンチ', rate: 10, ailment: 'やけど' },
  { name: 'めらめらバーン', rate: 100, ailment: 'やけど' },
  { name: 'れんごく', rate: 100, ailment: 'やけど' },
  { name: 'キラースピン', rate: 100, ailment: 'どく' },
  { name: 'クロスポイズン', rate: 10, ailment: 'どく' },
  { name: 'シェルアームズ', rate: 20, ailment: 'どく' },
  { name: 'スモッグ', rate: 40, ailment: 'どく' },
  { name: 'ダストシュート', rate: 30, ailment: 'どく' },
  { name: 'ダブルニードル', rate: 20, ailment: 'どく' },
  { name: 'どくづき', rate: 30, ailment: 'どく' },
  { name: 'どくばり', rate: 30, ailment: 'どく' },
  { name: 'どくばりセンボン', rate: 50, ailment: 'どく' },
  { name: 'ヘドロウェーブ', rate: 10, ailment: 'どく' },
  { name: 'ヘドロこうげき', rate: 30, ailment: 'どく' },
  { name: 'ヘドロばくだん', rate: 30, ailment: 'どく' },
  { name: 'ポイズンアクセル', rate: 30, ailment: 'どく' },
  { name: 'ポイズンテール', rate: 10, ailment: 'どく' },
  { name: 'どくどくのキバ', rate: 50, ailment: 'もうどく' },
  { name: 'いにしえのうた', rate: 10, ailment: 'ねむり' },
]

const additionalEffectConfuse = [
  { name: 'おしゃべり', rate: 100 },
  { name: 'かかとおとし', rate: 30 },
  { name: 'サイケこうせん', rate: 10 },
  { name: 'シグナルビーム', rate: 10 },
  { name: 'ねんりき', rate: 10 },
  { name: 'ばくれつパンチ', rate: 100 },
  { name: 'ぼうふう', rate: 30 },
  { name: 'ピヨピヨパンチ', rate: 20 },
  { name: 'マジカルアクセル', rate: 30 },
  { name: 'みずのはどう', rate: 20 },
  { name: 'ロッククライム', rate: 20 },
  { name: 'ワンダースチーム', rate: 20 },
]

const additionalEffectOthers = [
  'アンカーショット',
  'いっちょうあがり',
  'うたかたのアリア',
  'オリジンズスーパーノヴァ',
  'かげぬい',
  'がんせきアックス',
  'ジェットパンチ',
  'しおづけ',
  'じごくづき',
  'しっとのほのお',
  'トライアタック',
  'ひけん・ちえなみ',
  'ひみつのちから',
  'フェイタルクロー',
  'ぶきみなじゅもん',
]

const berryTable: BerryData[] = [
  { number: 1, name: 'クラボのみ', half: null, fling: true, naturalGift: { type: 'Fire', power: 80 } },
  { number: 2, name: 'カゴのみ', half: null, fling: true, naturalGift: { type: 'Water', power: 80 } },
  { number: 3, name: 'モモンのみ', half: null, fling: true, naturalGift: { type: 'Electric', power: 80 } },
  { number: 4, name: 'チーゴのみ', half: null, fling: true, naturalGift: { type: 'Grass', power: 80 } },
  { number: 5, name: 'ナナシのみ', half: null, fling: true, naturalGift: { type: 'Ice', power: 80 } },
  { number: 6, name: 'ヒメリのみ', half: null, fling: true, naturalGift: { type: 'Fighting', power: 80 } },
  { number: 7, name: 'オレンのみ', half: null, fling: true, naturalGift: { type: 'Poison', power: 80 } },
  { number: 8, name: 'キーのみ', half: null, fling: true, naturalGift: { type: 'Ground', power: 80 } },
  { number: 9, name: 'ラムのみ', half: null, fling: true, naturalGift: { type: 'Flying', power: 80 } },
  { number: 10, name: 'オボンのみ', half: null, fling: true, naturalGift: { type: 'Psychic', power: 80 } },
  { number: 11, name: 'フィラのみ', half: null, fling: true, naturalGift: { type: 'Fire', power: 80 } },
  { number: 12, name: 'ウイのみ', half: null, fling: true, naturalGift: { type: 'Rock', power: 80 } },
  { number: 13, name: 'マゴのみ', half: null, fling: true, naturalGift: { type: 'Ghost', power: 80 } },
  { number: 14, name: 'バンジのみ', half: null, fling: true, naturalGift: { type: 'Dragon', power: 80 } },
  { number: 15, name: 'イアのみ', half: null, fling: true, naturalGift: { type: 'Dark', power: 80 } },
  { number: 16, name: 'ズリのみ', half: null, fling: false, naturalGift: { type: 'Steel', power: 80 } },
  { number: 17, name: 'ブリーのみ', half: null, fling: false, naturalGift: { type: 'Fire', power: 90 } },
  { number: 18, name: 'ナナのみ', half: null, fling: false, naturalGift: { type: 'Water', power: 90 } },
  { number: 19, name: 'セシナのみ', half: null, fling: false, naturalGift: { type: 'Electric', power: 90 } },
  { number: 20, name: 'パイルのみ', half: null, fling: false, naturalGift: { type: 'Grass', power: 90 } },
  { number: 21, name: 'ザロクのみ', half: null, fling: false, naturalGift: { type: 'Ice', power: 90 } },
  { number: 22, name: 'ネコブのみ', half: null, fling: false, naturalGift: { type: 'Fighting', power: 90 } },
  { number: 23, name: 'タポルのみ', half: null, fling: false, naturalGift: { type: 'Poison', power: 90 } },
  { number: 24, name: 'ロメのみ', half: null, fling: false, naturalGift: { type: 'Ground', power: 90 } },
  { number: 25, name: 'ウブのみ', half: null, fling: false, naturalGift: { type: 'Flying', power: 90 } },
  { number: 26, name: 'マトマのみ', half: null, fling: false, naturalGift: { type: 'Psychic', power: 90 } },
  { number: 27, name: 'モコシのみ', half: null, fling: false, naturalGift: { type: 'Bug', power: 90 } },
  { number: 28, name: 'ゴスのみ', half: null, fling: false, naturalGift: { type: 'Rock', power: 90 } },
  { number: 29, name: 'ラブタのみ', half: null, fling: false, naturalGift: { type: 'Ghost', power: 90 } },
  { number: 30, name: 'ノメルのみ', half: null, fling: false, naturalGift: { type: 'Dragon', power: 90 } },
  { number: 31, name: 'ノワキのみ', half: null, fling: false, naturalGift: { type: 'Dark', power: 90 } },
  { number: 32, name: 'シーヤのみ', half: null, fling: false, naturalGift: { type: 'Steel', power: 90 } },
  { number: 33, name: 'カイスのみ', half: null, fling: false, naturalGift: { type: 'Fire', power: 100 } },
  { number: 34, name: 'ドリのみ', half: null, fling: false, naturalGift: { type: 'Water', power: 100 } },
  { number: 35, name: 'ベリブのみ', half: null, fling: false, naturalGift: { type: 'Electric', power: 100 } },
  { number: 36, name: 'オッカのみ', half: 'Fire', fling: false, naturalGift: { type: 'Fire', power: 80 } },
  { number: 37, name: 'イトケのみ', half: 'Water', fling: false, naturalGift: { type: 'Water', power: 80 } },
  { number: 38, name: 'ソクノのみ', half: 'Electric', fling: false, naturalGift: { type: 'Electric', power: 80 } },
  { number: 39, name: 'リンドのみ', half: 'Grass', fling: false, naturalGift: { type: 'Grass', power: 80 } },
  { number: 40, name: 'ヤチェのみ', half: 'Ice', fling: false, naturalGift: { type: 'Ice', power: 80 } },
  { number: 41, name: 'ヨプのみ', half: 'Fighting', fling: false, naturalGift: { type: 'Fighting', power: 80 } },
  { number: 42, name: 'ビアーのみ', half: 'Poison', fling: false, naturalGift: { type: 'Poison', power: 80 } },
  { number: 43, name: 'シュカのみ', half: 'Ground', fling: false, naturalGift: { type: 'Ground', power: 80 } },
  { number: 44, name: 'バコウのみ', half: 'Flying', fling: false, naturalGift: { type: 'Flying', power: 80 } },
  { number: 45, name: 'ウタンのみ', half: 'Psychic', fling: false, naturalGift: { type: 'Psychic', power: 80 } },
  { number: 46, name: 'タンガのみ', half: 'Bug', fling: false, naturalGift: { type: 'Bug', power: 80 } },
  { number: 47, name: 'ヨロギのみ', half: 'Rock', fling: false, naturalGift: { type: 'Rock', power: 80 } },
  { number: 48, name: 'カシブのみ', half: 'Ghost', fling: false, naturalGift: { type: 'Ghost', power: 80 } },
  { number: 49, name: 'ハバンのみ', half: 'Dragon', fling: false, naturalGift: { type: 'Dragon', power: 80 } },
  { number: 50, name: 'ナモのみ', half: 'Dark', fling: false, naturalGift: { type: 'Dark', power: 80 } },
  { number: 51, name: 'リリバのみ', half: 'Steel', fling: false, naturalGift: { type: 'Steel', power: 80 } },
  { number: 52, name: 'ホズのみ', half: 'Normal', fling: false, naturalGift: { type: 'Normal', power: 80 } },
  { number: 53, name: 'チイラのみ', half: null, fling: true, naturalGift: { type: 'Grass', power: 100 } },
  { number: 54, name: 'リュガのみ', half: null, fling: true, naturalGift: { type: 'Ice', power: 100 } },
  { number: 55, name: 'カムラのみ', half: null, fling: true, naturalGift: { type: 'Fighting', power: 100 } },
  { number: 56, name: 'ヤタピのみ', half: null, fling: true, naturalGift: { type: 'Poison', power: 100 } },
  { number: 57, name: 'ズアのみ', half: null, fling: true, naturalGift: { type: 'Ground', power: 100 } },
  { number: 58, name: 'サンのみ', half: null, fling: true, naturalGift: { type: 'Flying', power: 100 } },
  { number: 59, name: 'スターのみ', half: null, fling: true, naturalGift: { type: 'Psychic', power: 100 } },
  { number: 60, name: 'ナゾのみ', half: null, fling: false, naturalGift: { type: 'Bug', power: 100 } },
  { number: 61, name: 'ミクルのみ', half: null, fling: true, naturalGift: { type: 'Rock', power: 100 } },
  { number: 62, name: 'イバンのみ', half: null, fling: false, naturalGift: { type: 'Ghost', power: 100 } },
  { number: 63, name: 'ジャポのみ', half: null, fling: false, naturalGift: { type: 'Dragon', power: 100 } },
  { number: 64, name: 'レンブのみ', half: null, fling: false, naturalGift: { type: 'Dark', power: 100 } },
  { number: 65, name: 'ロゼルのみ', half: 'Fairy', fling: false, naturalGift: { type: 'Fairy', power: 80 } },
  { number: 66, name: 'アッキのみ', half: null, fling: true, naturalGift: { type: 'Fairy', power: 100 } },
  { number: 67, name: 'タラプのみ', half: null, fling: true, naturalGift: { type: 'Dark', power: 100 } },
]

const moveEffectMyRank: MoveEffectRank[] = [
  { name: 'アーマーキャノン', change: { attack: 0, defense: -1, specialAttack: 0, specialDefense: -1, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'アームハンマー', change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: -1, accuracy: 0, evasion: 0 } },
  { name: 'アイスハンマー', change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: -1, accuracy: 0, evasion: 0 } },
  { name: 'いじげんラッシュ', change: { attack: 0, defense: -1, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'インファイト', change: { attack: 0, defense: -1, specialAttack: 0, specialDefense: -1, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'オーバーヒート', change: { attack: 0, defense: 0, specialAttack: -2, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'ガリョウテンセイ', change: { attack: 0, defense: -1, specialAttack: 0, specialDefense: -1, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'ゴールドラッシュ', change: { attack: 0, defense: 0, specialAttack: -1, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'サイコブースト', change: { attack: 0, defense: 0, specialAttack: -2, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'スケイルショット', change: { attack: 0, defense: -1, specialAttack: 0, specialDefense: 0, speed: 1, accuracy: 0, evasion: 0 } },
  { name: 'スケイルノイズ', change: { attack: 0, defense: -1, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'ばかぢから', change: { attack: -1, defense: -1, specialAttack: 0, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'Vジェネレート', change: { attack: 0, defense: -1, specialAttack: 0, specialDefense: -1, speed: -1, accuracy: 0, evasion: 0 } },
  { name: 'ぶちかまし', change: { attack: 0, defense: -1, specialAttack: 0, specialDefense: -1, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'フルールカノン', change: { attack: 0, defense: 0, specialAttack: -2, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'ホイールスピン', change: { attack: 0, defense: 0, specialAttack: 0, specialDefense: 0, speed: -2, accuracy: 0, evasion: 0 } },
  { name: 'リーフストーム', change: { attack: 0, defense: 0, specialAttack: -2, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
  { name: 'りゅうせいぐん', change: { attack: 0, defense: 0, specialAttack: -2, specialDefense: 0, speed: 0, accuracy: 0, evasion: 0 } },
]

// 連続攻撃技
const continuousAttackMoveList = [
  { name: 'ギアソーサー', count: 2 },
  { name: 'ダブルアタック', count: 2 },
  { name: 'ダブルウィング', count: 2 },
  { name: 'ダブルチョップ', count: 2 },
  { name: 'ダブルニードル', count: 2 },
  { name: 'ダブルパンツァー', count: 2 },
  { name: 'ツインビーム', count: 2 },
  { name: 'ドラゴンアロー', count: 2 },
  { name: 'にどげり', count: 2 },
  { name: 'ホネブーメラン', count: 2 },
  { name: 'すいりゅうれんだ', count: 3 },
  { name: 'トリプルダイブ', count: 3 },
  { name: 'おうふくビンタ', count: 5 },
  { name: 'スイープビンタ', count: 5 },
  { name: 'スケイルショット', count: 5 },
  { name: 'タネマシンガン', count: 5 },
  { name: 'たまなげ', count: 5 },
  { name: 'つっぱり', count: 5 },
  { name: 'つららばり', count: 5 },
  { name: 'とげキャノン', count: 5 },
  { name: 'ボーンラッシュ', count: 5 },
  { name: 'ミサイルばり', count: 5 },
  { name: 'みずしゅりけん', count: 5 },
  { name: 'みだれづき', count: 5 },
  { name: 'みだれひっかき', count: 5 },
  { name: 'れんぞくパンチ', count: 5 },
  { name: 'ロックブラスト', count: 5 },
  { name: 'トリプルキック', count: 1 },
  { name: 'トリプルアクセル', count: 1 },
  { name: 'ネズミざん', count: 10 },
  { name: 'ふくろだたき', count: 0 },
]

// 与ダメージ依存反動技
const dependentRecoilMoveList = [
  { name: 'アフロブレイク', rate: 0.25 },
  { name: 'ウェーブタックル', rate: 0.33 },
  { name: 'ウッドハンマー', rate: 0.33 },
  { name: 'じごくぐるま', rate: 0.25 },
  { name: 'すてみタックル', rate: 0.33 },
  { name: 'とっしん', rate: 0.25 },
  { name: 'はめつのひかり', rate: 0.50 },
  { name: 'フレアドライブ', rate: 0.33 },
  { name: 'ブレイブバード', rate: 0.33 },
  { name: 'ボルテッカー', rate: 0.33 },
  { name: 'もろはのずつき', rate: 0.50 },
  { name: 'ワイルドボルト', rate: 0.25 },
]

// 与ダメージ非依存反動技
const independentRecoilMoveList = [
  { name: 'クロロブラスト', rate: 0.50 },
  { name: 'わるあがき', rate: 0.25 }
]



const paradoxPokemonList = [
  'イダイナキバ',
  'サケブシッポ',
  'アラブルタケ',
  'ハバタクカミ',
  'チヲハウハネ',
  'スナノケガワ',
  'トドロクツキ',
  'コライドン',
  'ウネルミナモ',
  'テツノワダチ',
  'テツノツツミ',
  'テツノカイナ',
  'テツノドクガ',
  'テツノイバラ',
  'テツノブジン',
  'ミライドン',
  'テツノイサハ'
]

const protectMoveList = [
  'まもる',
  'こらえる',
  'みきり',
  'ニードルガード',
  'キングシールド',
  'トーチカ',
  'ブロッキング',
  'ダイウォール'
]

const storeMoveList: string[] = [
  'かまいたち',
  'コールドフレア',
  'ゴッドバード',
  'ジオコントロール',
  'ソーラービーム',
  'ソーラブレード',
  'フリーズボルト',
  'メテオビーム',
  'ロケットずつき',
  'あなをほる',
  'そらをとぶ',
  'とびはねる',
  'フリーフォール',
  'ダイビング',
  'ゴーストダイブ',
  'シャドーダイブ'
]

const notMaxGuardMoveList: string[] = [
  'アシストギア',
  'おちゃかい',
  'じこあんじ',
  'じばそうさ',
  'テクスチャー2',
  'とおせんぼう',
  'フラワーガード',
  'へんしん',
  'ゴーストダイブ',
  'シャドーダイブ'
]
