const typeTextMaster: {
  id: number,
  nameEN: PokemonType,
  nameJA: string
}[] = [
  { id: 1, nameEN: 'NORMAL', nameJA: 'ノーマル' },
  { id: 2, nameEN: 'FIGHTING', nameJA: 'かくとう' },
  { id: 3, nameEN: 'FLYING', nameJA: 'ひこう' },
  { id: 4, nameEN: 'POISON', nameJA: 'どく' },
  { id: 5, nameEN: 'GROUND', nameJA: 'じめん' },
  { id: 6, nameEN: 'ROCK', nameJA: 'いわ' },
  { id: 7, nameEN: 'BUG', nameJA: 'むし' },
  { id: 8, nameEN: 'GHOST', nameJA: 'ゴースト' },
  { id: 9, nameEN: 'STEEL', nameJA: 'はがね' },
  { id: 10, nameEN: 'FIRE', nameJA: 'ほのお' },
  { id: 11, nameEN: 'WATER', nameJA: 'みず' },
  { id: 12, nameEN: 'GRASS', nameJA: 'くさ' },
  { id: 13, nameEN: 'ELECTRIC', nameJA: 'でんき' },
  { id: 14, nameEN: 'PSYCHIC', nameJA: 'エスパー' },
  { id: 15, nameEN: 'ICE', nameJA: 'こおり' },
  { id: 16, nameEN: 'DRAGON', nameJA: 'ドラゴン' },
  { id: 17, nameEN: 'DARK', nameJA: 'あく' },
  { id: 18, nameEN: 'FAIRY', nameJA: 'フェアリー' },
  { id: 19, nameEN: null, nameJA: '' },
]
