const typeTextMaster: {
  id: number,
  nameEN: PokemonType,
  nameJA: string
}[] = [
  { id: 1, nameEN: 'Normal', nameJA: 'ノーマル' },
  { id: 2, nameEN: 'Fighting', nameJA: 'かくとう' },
  { id: 3, nameEN: 'Flying', nameJA: 'ひこう' },
  { id: 4, nameEN: 'Poison', nameJA: 'どく' },
  { id: 5, nameEN: 'Ground', nameJA: 'じめん' },
  { id: 6, nameEN: 'Rock', nameJA: 'いわ' },
  { id: 7, nameEN: 'Bug', nameJA: 'むし' },
  { id: 8, nameEN: 'Ghost', nameJA: 'ゴースト' },
  { id: 9, nameEN: 'Steel', nameJA: 'はがね' },
  { id: 10, nameEN: 'Fire', nameJA: 'ほのお' },
  { id: 11, nameEN: 'Water', nameJA: 'みず' },
  { id: 12, nameEN: 'Grass', nameJA: 'くさ' },
  { id: 13, nameEN: 'Electric', nameJA: 'でんき' },
  { id: 14, nameEN: 'Psychic', nameJA: 'エスパー' },
  { id: 15, nameEN: 'Ice', nameJA: 'こおり' },
  { id: 16, nameEN: 'Dragon', nameJA: 'ドラゴン' },
  { id: 17, nameEN: 'Dark', nameJA: 'あく' },
  { id: 18, nameEN: 'Fairy', nameJA: 'フェアリー' },
  { id: 19, nameEN: null, nameJA: '' },
]
