const typeTextMaster: {
  id: number,
  nameEN: PokemonType,
  nameJA: string
}[] = [
  { id: 1, nameEN: 'normal', nameJA: 'ノーマル' },
  { id: 2, nameEN: 'fighting', nameJA: 'かくとう' },
  { id: 3, nameEN: 'flying', nameJA: 'ひこう' },
  { id: 4, nameEN: 'poison', nameJA: 'どく' },
  { id: 5, nameEN: 'ground', nameJA: 'じめん' },
  { id: 6, nameEN: 'rock', nameJA: 'いわ' },
  { id: 7, nameEN: 'bug', nameJA: 'むし' },
  { id: 8, nameEN: 'ghost', nameJA: 'ゴースト' },
  { id: 9, nameEN: 'steel', nameJA: 'はがね' },
  { id: 10, nameEN: 'fire', nameJA: 'ほのお' },
  { id: 11, nameEN: 'water', nameJA: 'みず' },
  { id: 12, nameEN: 'grass', nameJA: 'くさ' },
  { id: 13, nameEN: 'electric', nameJA: 'でんき' },
  { id: 14, nameEN: 'psychic', nameJA: 'エスパー' },
  { id: 15, nameEN: 'ice', nameJA: 'こおり' },
  { id: 16, nameEN: 'dragon', nameJA: 'ドラゴン' },
  { id: 17, nameEN: 'dark', nameJA: 'あく' },
  { id: 18, nameEN: 'fairy', nameJA: 'フェアリー' },
  { id: 19, nameEN: null, nameJA: '' },
]
